### PR TITLE
Fix masking of Hovmoller plots on different meshes

### PR DESCRIPTION
**Pull request by xylar**
We want the more restrictive mask (with shallower bathymetry) for comparing Hovmoller plots on different meshes.

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I ran Hovmoller comparison analysis between the SORRM and EC meshes that had previously failed.  With these changes, it was successful:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis/AGU-22/LR_vs_SORRM-N2/yrs71-100/

**Comment by xylar** [comment]
@darincomeau, could you verify that this fixes the problem for you, too?

**Comment by darincomeau** [comment]
Thanks @xylar! I ended up testing this on the same set of runs, and it indeed worked for me:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.dcomeau/AGU-22/LR_vs_SORRM-N2/yrs1-5/ocean/index.html

**Comment by xylar** [comment]
Thanks @darincomeau!

**Pull request merged**
