### PR TITLE
Iterate over region masks in oceanRegionalProfile sums

### LINKED ISSUE #787: Performance issue with oceanRegionalProfiles task
On anvil, I have encountered the following error, when using 12 parallel tasks:
```
Compute time series of regional profiles...
analysis task oceanRegionalProfiles_computeOceanBasinsProfiles_0003-0003 failed during run
Traceback (most recent call last):
  File "/gpfs/fs1/home/ac.milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/shared/analysis_task.py", line 330, in run
    self.run_task()
  File "/gpfs/fs1/home/ac.milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/ocean/ocean_regional_profiles.py", line 361, in run_task
    totalArea = (cellMasks * areaCell * vertMask).sum('nCells')
  File "/home/ac.milena/.conda/envs/mpas-analysis/lib/python3.8/site-packages/xarray/core/dataarray.py", line 2991, in func
    f(self.variable, other_variable)
  File "/home/ac.milena/.conda/envs/mpas-analysis/lib/python3.8/site-packages/xarray/core/variable.py", line 2301, in func
    f(self_data, other_data)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 3.43 GiB for an array with shape (9, 851664, 60) and data type float64
```

### PR DESCRIPTION
**Pull request by xylar**
This should eliminate out-of-memory errors that have been happening.

closes #787

### CODE REVIEW

**Comment by xylar** [comment]
@darincomeau, I'm still testing this but a test on the run
```
20210120.A_WCYCL1850S_CMIP6.ne30pg2_SOwISC12to60E2r4.beta1.maptest.anvil/yrs61-70
```
with just the `oceanRegionalProfiles` task took about 30 minutes and finished without any errors on Chrysalis on 6 parallel tasks.

**Comment by xylar** [comment]
```
20210326.v2beta3.piControl.ne30pg2_WCAtl12to45E2r4
```
also seems to be running without issues with 6 parallel tasks.

**Comment by darincomeau** [comment]
I'm about to run analysis on years 91-100 for `20210326.v2beta3.piControl.ne30pg2_WCAtl12to45E2r4`; I'll use this branch.

**Comment by xylar** [comment]
@darincomeau, you may need to create a custom conda environment for `mpas-analysis` following the README.  There have been a lot of recent updates.

**Comment by xylar** [comment]
Thanks for testing!

**Comment by darincomeau** [comment]
@xylar yes I deleted my old mpas-analysis environment and installing a new one now (I remembered this time!).

**Comment by milenaveneziani** [comment]
@xylar, I think I speak on behalf of everybody when I say: thank you for your patience. I fully acknowledge that you must have told us 99 times that we need to create our own conda environment when testing new development in MPAS-Analysis, Tools or geometric_features. Everytime I, personally, forget and then after the fact I say to myself "yes, Xylar told me about this before"....

**Comment by xylar** [comment]
@milenaveneziani, I wasn't going to make you review this one.  But you can, of course, I'm just asking a lot of you lately.

**Comment by milenaveneziani** [comment]
Thanks @xylar. If I am running an analysis today, I'll use this branch. But if @darincomeau's test passes and you'd like to merge, please go ahead.

**Comment by darincomeau** [comment]
My analysis got stuck on and seemed to hang `timeSeriesTransport_TransportTransects`, which I suspect is unrelated here. Trying again now.

**Comment by xylar** [comment]
> My analysis got stuck on and seemed to hang `timeSeriesTransport_TransportTransects`, which I suspect is unrelated here. Trying again now.

Yeah, probably just turn that off for now.  We really need all of the PRs that I'm working on for a full, proper test to be possible.  It's making testing very difficult for all of us, I know.  Hopefully, things will just be better soon.

**Comment by milenaveneziani** [comment]
I now have my environment ready to test #794 (on blues). Why don't I go ahead with that, and we can restart testing of this after #794, and #793, are in?

**Comment by xylar** [comment]
@milenaveneziani, that was my plan, too.  But @darincomeau may only want to test this PR, in which case it doesn't have to wait for the other PRs as long as MOC and transport transects are turned off.

**Comment by darincomeau** [comment]
What I should have done is just put this task back in the previous analysis that was failing due to this error, which would have been much quicker and cleaner. I'll do that now.

**Comment by darincomeau** [comment]
Ok success! I ran with the `WCAtl12to45E2r4` mesh that was previously giving me OOM errors for this task. I had to disable `'no_timeSeriesTransport', 'no_moc'` to get the analysis to complete using this branch, but I don't think that matters for this PR.

Thanks @xylar !

**Review by darincomeau — APPROVED** [review]
Approved based on successful testing with a situation I had previously run into this error.

**Comment by xylar** [comment]
Thanks very much @darincomeau.  I'm going to wait to test this until I merge #793 and #794, and rebase but I will not ask you to do any further testing.

**Comment by xylar** [comment]
## Testing


This has been tested with the Anvil and Chrysalis test suites:
* [Anvil](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/anvil/fix_oom_in_ocean_regional_profiles/)
* [Chrysalis](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/chrysalis/fix_oom_in_ocean_regional_profiles/)

I also tested on a simulation with 2 larger meshes because this is where the performance issue came up before.  I just ran the `oceanRegionalProfiles` task:
* [WCAtl12to45E2r4](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/chrysalis/fix_oom_in_ocean_regional_profiles/20210326.v2beta3.piControl.ne30pg2_WCAtl12to45E2r4/ocean/index.html)
* [SOwISC12to60E2r4](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/chrysalis/fix_oom_in_ocean_regional_profiles/20210120.A_WCYCL1850S_CMIP6.ne30pg2_SOwISC12to60E2r4.beta1.maptest.anvil/yrs61-70/ocean/index.html) but I'm rerunning this one with `polarRegions.conf` included so we get the Hovmoller plots, too.

**Pull request merged**
