### PR TITLE
Transect contour plots

### PR DESCRIPTION
**Pull request by gstreletz**
Added the ability to compare the model and reference fields on transects by plotting the contours of both fields on a single plot (as an alternative to the default mode of plotting the model and reference fields and their difference as heatmaps on a three panel plot).

New parameters in the [transects] section of config.default control which comparison mode (three panel plot or contour comparison plot) is used, what the line style and line color of contours are (controlled separately for the contours on heatmaps or of the model field on contour comparison plots vs. the contours of the reference field on contour comparison plots), whether to label the contours, and what precision to use for the contour labels.

These parameters can later be moved to the config.default section for specific types of transects if more granularity of control is desired.

Note that the new option to label contours also applied to the optional contours on heatmaps (controlled by a separate parameter in the [transects] section of config.default).

The ability to use zero, one, or two upper x axes -- recently implemented for heatmap transect plots -- also applies to the contour comparison plots.

A legend below the contour comparison plot indicates which contours are for the model and which are for the reference field.  If contour labels are used, the colorbar label string (typically containing the units of the field) is parenthetically appended to the legend entries.  If contour comparison plot mode is enabled and there is no comparison field, just contours of the model field are plotted.  In this case, the colorbar label string (units) is parenthetically appended to the plot title, as no legend is used.

The following galleries show some sample contour comparison plots for a few different combinations of parameters:

http://portal.nersc.gov/project/acme/streletz/1_contourComparisonPlot_no_upper_axis_contour_labels_html/ocean/index.html#woce

http://portal.nersc.gov/project/acme/streletz/2_contourComparisonPlot_greatestExtent_upper_axis_no_contour_labels_html/ocean/#woce

http://portal.nersc.gov/project/acme/streletz/3_contourComparisonPlot_both_upper_axes_contour_labels_html/ocean/#woce

Note that this PR mostly (but not entirely addresses issue #230, Add Drake Passage PD plotting).  The type of plot requested there is provided by this PR.  In order create such a plot for the Drake Passage, all that is needed is to create a GeoJSON file for the Drake Passage transect).

### CODE REVIEW

**Comment by xylar** [comment]
Here is the "official" MPAS definition of the Drake Passage:
https://github.com/MPAS-Dev/geometric_features/blob/master/ocean/transect/Drake_Passage/transect.geojson

I will try this out!

**Comment by milenaveneziani** [comment]
I don't have time to test this now, so I will remove myself as reviewer.
I did check the plots/links though, and I have two simple comments: 1) I would make writing of the labels a default (without them we have no way to compare the two sets of curves) and 2) maybe make the observations simply red lines, instead of dashed (sometimes dashed lines are used for negative values).

Thanks @gstreletz for adding this functionality!

**Comment by xylar** [comment]
@gstreletz, I will take care of the remaining steps to make a plot of the Drake Passage potential density a default output from the analysis.  This will involve some decisions about how to download the geojson file from the `geometric_features` repo and will likely involve moving at least the `compareAsContoursOnSinglePlot` to the section for each transect task.

**Comment by xylar** [comment]
@milenaveneziani, the contour labels are on by default in a comparison plot:
https://github.com/MPAS-Dev/MPAS-Analysis/pull/450/files#diff-2293ae9d07bf74f60774b40c487a4ae8R1203
They are off if a "heat map" (i.e. a plot with a color map) is being plotted:
https://github.com/MPAS-Dev/MPAS-Analysis/pull/450/files#diff-2293ae9d07bf74f60774b40c487a4ae8R1200

I think this is the functionality we want.

I agree with making both contours solid by default.

**Comment by xylar** [comment]
Here's a first stab at the Drake Passage:

potentialdensity_drake_passage_20180514 g oqu240wli edison_ann_years0002-0008

The maximum depth almost certainly needs to be changed (and obviously I need another run to compare against to get the full effect) but I think @gstreletz has implemented all the other functionality we need.

**Comment by milenaveneziani** [comment]
> I think this is the functionality we want.

great. thanks for clarifying.

**Comment by xylar** [comment]
@gstreletz, I think we're just waiting for a quick fix to change "dashed" to "solid" and this is ready to merge.

**Comment by gstreletz** [comment]
> @gstreletz, I think we're just waiting for a quick fix to change "dashed" to "solid" and this is ready to merge.

Done.

**Comment by xylar** [comment]
Again, great work, @gstreletz!

**Pull request merged**
