### PR TITLE
Add 2 new transects to transport time series

### PR DESCRIPTION
**Pull request by xylar**
These are new in geometric_features.  They are hand-drawn so there are no associated obs.

### CODE REVIEW

**Review by milenaveneziani — COMMENTED** [review]
oh we can find some obs, as I took the transect from a paper that mentioned observations (cruise data). I need to find the range though. Is that ok if I do this later this afternoon?

**Comment by xylar** [comment]
Oh, great!, no rush.

**Comment by milenaveneziani** [comment]
@xylar: I found various papers with obs estimates, but they focus on either the overflow water at Denmark Strait (sigma0 higher than 27.8) or on the inflow of Atlantic Water through the Greenland Scotland Ridge, not net volume transport (I estimate that 5-6 Sv flow out of Denmark St and ~4 Sv go in through the Iceland-Faroe-Scotland channels, but this is too vague to put in there). So, let us leave the obs blank for now.

**Review by milenaveneziani — APPROVED** [review]

**Comment by milenaveneziani** [comment]
@xylar: since you rebased this one onto #792, how about I test with this branch?

**Comment by xylar** [comment]
Sounds great!  That's what I'm doing as well.

**Comment by milenaveneziani** [comment]
Test with `WCAtl12to45E2r4` is moving along nicely on anvil.

**Comment by milenaveneziani** [comment]
@xylar: the two transects should also be added to `config.default`:
```
[timeSeriesTransport]
## options related to plotting time series of transport through transects

# list of ocean transects from geometric_features to plot or ['all'] for all
# available transects.
transectsToPlot = ['Drake Passage', 'Tasmania-Ant', 'Africa-Ant', 'Antilles Inflow',
                   'Mona Passage', 'Windward Passage', 'Florida-Cuba', 'Florida-Bahamas',
                   'Indonesian Throughflow', 'Agulhas', 'Mozambique Channel', 'Bering Strait',
                   'Lancaster Sound', 'Fram Strait', 'Nares Strait', 'Denmark Strait',
                   'Iceland-Faroe-Scotland']
```

**Comment by xylar** [comment]
Oh, good catch.  I will add them.

**Comment by xylar** [comment]
Shoot, that probably means my testing is useless.

**Comment by milenaveneziani** [comment]
Yes, for this specific PR, my test was also useless, but for #792 things worked for me (test just passed).
I am going to rerun it with the two extra transects.

**Comment by milenaveneziani** [comment]
@xylar: here is the result of my test with the two transects added to the config file:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.milena/20210326.v2beta3.piControl.ne30pg2_WCAtl12to45E2r4/testPR791/Years11-20/ocean/index.html#transporttime

Once `config.default` is revised, you could merge this (as well as #792).

**Comment by xylar** [comment]
@milenaveneziani, thanks so much for your testing!

In my testing, it took almost 2 hours to make the transport transects for the `WCAtl12to45E2r4` mesh.  That definitely suggests to me that something is still wrong.  I suspect it was running on one core but I need to investigate tomorrow (too tired tonight!).

**Comment by xylar** [comment]
## Testing

This has been tested with the Anvil and Chrysalis test suites:
* [Anvil](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/anvil/add_new_transects_to_transport_time_series/)
* [Chrysalis](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/chrysalis/add_new_transects_to_transport_time_series/)

I also tested on a simulation with 3 larger meshes to make sure the MOC looks as expected:
* [WCAtl12to45E2r4](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/chrysalis/add_new_transects_to_transport_time_series/20210326.v2beta3.piControl.ne30pg2_WCAtl12to45E2r4/ocean/index.html#transporttime)
* [WC14to60E2r3](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/chrysalis/add_new_transects_to_transport_time_series/20210305.v2beta3.piControl.naRRMpg2_WC14to60E2r3.chrysalis/ts_0001-0200_climo_0151-0200/ocean/index.html#transporttime)
* [SOwISC12to60E2r4.beta1](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/chrysalis/add_new_transects_to_transport_time_series/20210120.A_WCYCL1850S_CMIP6.ne30pg2_SOwISC12to60E2r4.beta1.maptest.anvil/yrs61-70/ocean/index.html#transporttime)

The two new transport time series are now showing up, e.g.:
Denmark Strait:
image

Iceland-Faroe-Scotland:
image

**Pull request merged**
