### PR TITLE
Added 0 contour in MOC global

### PR DESCRIPTION
**Pull request by milenaveneziani**
This adds a 0 contour in the Global plot of the MOC streamfunction in `config.default`.
It also adds the computation of the `IndoPacific` MOC by default.

### CODE REVIEW

**Comment by milenaveneziani** [comment]
@xylar: I am running a quick test now just to show how the plots turn out with these changes.

**Comment by milenaveneziani** [comment]
Here is the link with the plots generated by this PR:
https://compy-dtn.pnl.gov/vene705/E3SMv2alpha/mpas-analysis/20201108.alpha5_55_fallback.piControl.ne30pg2_r05_EC30to60E2r2-1900_ICG.compy/Test/ocean/index.html

**Comment by xylar** [comment]
@milenaveneziani, this looks excellent to me!  I'm running some tests on Anvil right now.  I suspect I might need to update the test suite to disable the IndoPacific MOC there depending on the settings but let's find out.

**Review by xylar — APPROVED** [review]
I tested this using the updated suite in #779 and it worked great.  Results are here:

https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/add0contourMOCglobal/

The MOC obviously doesn't look good at QU240wLI or QU480 resolution, but it's there, including for the Indo-pacific.
image

**Comment by xylar** [comment]
@vanroekel, would you make sure this serves your needs for the AMOC working group?

**Review by vanroekel — APPROVED** [review]
approving by examination of plots.  These look great and are exactly what we need.  Thanks for the quick work @milenaveneziani

**Comment by xylar** [comment]
@milenaveneziani, given that we've both approved, I'm going to go ahead and merge this.  I know you assigned yourself so I hope you don't mind.

**Comment by milenaveneziani** [comment]
Great, thanks.

**Pull request merged**
