### PR TITLE
Refactor BGC so it is one task, not one per field

### PR DESCRIPTION
**Pull request by xylar**
This should make it easier to compute a table of skill scores for all the requested BGC in a future merge.

### CODE REVIEW

**Comment by xylar** [comment]
@pwolfram and @bradyrx, I need to test this out on a BGC run (for which I'll use one or another of the example config files).  If either of you have comments or concerns about the changes I've made in this refactor, let me know.

**Comment by xylar** [comment]
@pwolfram, I noticed that at the end of the day yesterday but haven't had a chance to fix it yet. I'll let you know when this is ready for you to take another look.

**Comment by pwolfram** [comment]
Thanks @xylar!

**Comment by xylar** [comment]
@pwolfram, I believe I have fixed the issues.  I'm testing now on Grizzly.  Please feel free to redo your testing as well.

**Comment by xylar** [comment]
My grizzly test (with the updated `configs/lanl/config.BGCphaeo4.testrun`) was successful.  Note: @milenaveneziani, I had to replace the mapping file for oEC60to30v3 in `diagnostics/mpas_analysis/maps` on LANL IC, since the existing one you had placed there was invalid.  My guess is that the upload just didn't complete successfully.  Something to check when we update the diagnostics on all the supported machines, including LANL IC.

**Comment by xylar** [comment]
That's a very good idea.

**Comment by pwolfram** [comment]
@xylar, did you want to add a `checksum` command or is this ready to test as-is?

**Comment by xylar** [comment]
@pwolfram, the issue with the mapping  file is completely unrelated to this PR other than the fact that the BGC run used to test this branch happened to use the mapping file that was corrupted.  The checksum would be added to a script that downloads the observations, and would need to be done in a separate commit.  It is also not needed to test this branch.

Please proceed with you resting.

**Comment by pwolfram** [comment]
Great @xylar, I've tested this and it works and can be merged.  Just to be clear, this *doesn't* have the skill score information, correct?

**Comment by xylar** [comment]
@pwolfram.  That's correct.  The skill score work wasn't ready to merge as I understand it.

**Comment by pwolfram** [comment]
Just to clarify here @xylar, I need to simply rebase the branch we were working on together now to develop, right?

**Comment by xylar** [comment]
Yes, a rebase would probably be a good idea but even that shouldn't be necessary if the the branch I just merged is still in your commit history.

**Pull request merged**
