### PR TITLE
Add support and docs for ncclimo "mpi" mode

### PR DESCRIPTION
**Pull request by xylar**
This should help with big data sets on cooley, where we've been running out of memory.

### CODE REVIEW

**Comment by xylar** [comment]
@darincomeau and @stephenprice, sorry for the moving target.  Could you try changing `bck` to `mpi` and running on multiple nodes?  (For now, 2 should do the trick but any number up to 12 should work I think.)  I think this should take care of the memory errors at the expense of one node sitting idle for the rest of the analysis once ncclimo tasks have finished.  I will test this out myself tomorrow when I get a chance.

**Comment by xylar** [comment]
@darincomeau and @stephenprice, don't bother testing yet.  I'm getting problems.

**Comment by xylar** [comment]
@czender, could you tell me if you can recommend anything based on the following error log?

```
Computing MPAS climatologies from files:
    mpaso.hist.am.timeSeriesStatsMonthly.0001-01-01.nc through
    mpaso.hist.am.timeSeriesStatsMonthly.0001-12-01.nc
running: ncclimo -4 --clm_md=mth -a sdd -m mpaso -p mpi -v timeMonthly_avg_activeTracers_salinity,timeMonthly_avg_activeTracers_temperature,timeMonthly_avg_dThreshMLD,timeMonthly_avg_landIceFreshwaterFlux,timeMonthly_avg_meridionalHeatTransportLat,timeMonthly_avg_meridionalHeatTransportLatZ,timeMonthly_avg_normalVelocity,timeMonthly_avg_potentialDensity,timeMonthly_avg_pressureAdjustedSSH,timeMonthly_avg_velocityMeridional,timeMonthly_avg_velocityZonal,timeMonthly_avg_vertVelocityTop --seasons=JFM,JAS,ANN -s 0001 -e 0001 -i /lus/theta-fs0/projects/OceanClimate_2/xylar/analysis/ncclimo_mpi/20190130.GMPAS-IAF-ISMF.T62_oRRS30to10v3wLI.theta/clim/mpas/source_symlinks -o /lus/theta-fs0/projects/OceanClimate_2/xylar/analysis/ncclimo_mpi/20190130.GMPAS-IAF-ISMF.T62_oRRS30to10v3wLI.theta/clim/mpas/unmasked_oRRS30to10v3wLI
Climatology operations invoked with command:
/lus/theta-fs0/projects/ccsm/acme/tools/e3sm-unified/base/envs/mpas_analysis_1.2.2/bin/ncclimo -4 --clm_md=mth -a sdd -m mpaso -p mpi -v timeMonthly_avg_activeTracers_salinity,timeMonthly_avg_activeTracers_temperature,timeMonthly_avg_dThreshMLD,timeMonthly_avg_landIceFreshwaterFlux,timeMonthly_avg_meridionalHeatTransportLat,timeMonthly_avg_meridionalHeatTransportLatZ,timeMonthly_avg_normalVelocity,timeMonthly_avg_potentialDensity,timeMonthly_avg_pressureAdjustedSSH,timeMonthly_avg_velocityMeridional,timeMonthly_avg_velocityZonal,timeMonthly_avg_vertVelocityTop --seasons=JFM,JAS,ANN -s 0001 -e 0001 -i /lus/theta-fs0/projects/OceanClimate_2/xylar/analysis/ncclimo_mpi/20190130.GMPAS-IAF-ISMF.T62_oRRS30to10v3wLI.theta/clim/mpas/source_symlinks -o /lus/theta-fs0/projects/OceanClimate_2/xylar/analysis/ncclimo_mpi/20190130.GMPAS-IAF-ISMF.T62_oRRS30to10v3wLI.theta/clim/mpas/unmasked_oRRS30to10v3wLI
Started climatology splitting at Sun Mar 10 21:18:38 UTC 2019
Running climatology script ncclimo from directory /lus/theta-fs0/projects/ccsm/acme/tools/e3sm-unified/base/envs/mpas_analysis_1.2.2/bin
NCO binaries version 4.7.9 from directory /lus/theta-fs0/projects/ccsm/acme/tools/e3sm-unified/base/envs/mpas_analysis_1.2.2/bin
Parallelism mode = MPI
Producing standard climatology from raw input files in directory /lus/theta-fs0/projects/OceanClimate_2/xylar/analysis/ncclimo_mpi/20190130.GMPAS-IAF-ISMF.T62_oRRS30to10v3wLI.theta/clim/mpas/source_symlinks
Output files to directory /lus/theta-fs0/projects/OceanClimate_2/xylar/analysis/ncclimo_mpi/20190130.GMPAS-IAF-ISMF.T62_oRRS30to10v3wLI.theta/clim/mpas/unmasked_oRRS30to10v3wLI
Climatology from 1 years of contiguous raw data touching 1 calendar years from YYYYMM = 000101 to 000112
Input filenames will be constructed with CESM'ish or E3SM/ACME'ish conventions
Each input file assumed to contain mean of one month
Winter statistics based on seasonally discontiguous December (sdd-mode): DJF sequences comprise three months from the same calendar year
Annotation for CF climatology attribute and climatology_bounds variable will be performed
This climatology will not be regridded
Generating climatology...
Climatological monthly mean for month 1 ...
Climatological monthly mean for month 2 ...
Climatological monthly mean for month 3 ...
Climatological monthly mean for month 4 ...
Climatological monthly mean for month 5 ...
Climatological monthly mean for month 6 ...
Climatological monthly mean for month 7 ...
Climatological monthly mean for month 8 ...
Climatological monthly mean for month 9 ...
Climatological monthly mean for month 10 ...
Climatological monthly mean for month 11 ...
Climatological monthly mean for month 12 ...

Usage: ./mpiexec [global opts] [local opts for exec1] [exec1] [exec1 args] : [local opts for exec2] [exec2] [exec2 args] : ...

Global options (passed to all executables):

  Global environment options:
    -genv {name} {value}             environment variable name and value
    -genvlist {env1,env2,...}        environment variable list to pass
    -genvnone                        do not pass any environment variables
    -genvall                         pass all environment variables not managed
                                          by the launcher (default)

  Other global options:
    -f {name}                        file containing the host names
    -hosts {host list}               comma separated host list
    -wdir {dirname}                  working directory to use
    -configfile {name}               config file containing MPMD launch options


Local options (passed to individual executables):

  Local environment options:
    -env {name} {value}              environment variable name and value
    -envlist {env1,env2,...}         environment variable list to pass
    -envnone                         do not pass any environment variables
    -envall                          pass all environment variables (default)

  Other local options:
    -n/-np {value}                   number of processes
    {exec_name} {args}               executable name and arguments


Hydra specific options (treated as global):

  Launch options:
    -launcher                        launcher to use (ssh rsh fork slurm ll lsf sge manual persist)
    -launcher-exec                   executable to use to launch processes
    -enable-x/-disable-x             enable or disable X forwarding

  Resource management kernel options:
    -rmk                             resource management kernel to use (user slurm ll lsf sge pbs cobalt)

  Processor topology options:
    -topolib                         processor topology library (hwloc)
    -bind-to                         process binding
    -map-by                          process mapping
    -membind                         memory binding policy

  Checkpoint/Restart options:
    -ckpoint-interval                checkpoint interval
    -ckpoint-prefix                  checkpoint file prefix
    -ckpoint-num                     checkpoint number to restart
    -ckpointlib                      checkpointing library (none)

  Demux engine options:
    -demux                           demux engine (poll select)

  Other Hydra options:
    -verbose                         verbose mode
    -info                            build information
    -print-all-exitcodes             print exit codes of all processes
    -iface                           network interface to use
    -ppn                             processes per node
    -profile                         turn on internal profiling
    -prepend-rank                    prepend rank to output
    -prepend-pattern                 prepend pattern to output
    -outfile-pattern                 direct stdout to file
    -errfile-pattern                 direct stderr to file
    -nameserver                      name server information (host:port format)
    -disable-auto-cleanup            don't cleanup processes on error
    -disable-hostname-propagation    let MPICH auto-detect the hostname
    -order-nodes                     order nodes as ascending/descending cores
    -localhost                       local hostname for the launching node
    -usize                           universe size (SYSTEM, INFINITE, <value>)

Please see the intructions provided at
http://wiki.mpich.org/mpich/index.php/Using_the_Hydra_Process_Manager
for further details
```

**Comment by xylar** [comment]
I am running from a conda environment that you should be able to access with:
```
source /lus/theta-fs0/projects/ccsm/acme/tools/e3sm-unified/base/etc/profile.d/conda.sh
conda activate mpas_analysis_1.2.2
```
I'm trying to run on 2 nodes:
```
#!/bin/bash
#COBALT -t 1:00:00
#COBALT -n 2
#COBALT -A OceanClimate_2
...
```

**Comment by xylar** [comment]
I suspect the problem is that we're running with `mpirun`, `mpiexec`, etc. from the conda environment, not form `cooley`'s built-in envrionment:
```
 $ which mpiexec
/lus/theta-fs0/projects/ccsm/acme/tools/e3sm-unified/base/envs/mpas_analysis_1.2.2/bin/mpiexec
$ conda deactivate
$ which mpiexec
/soft/libraries/mpi/mvapich2/gcc/bin/mpiexec
```
I don't know what to do about this because I have no way of loading `nco` in the conda package without getting `open-mpich` as well.

**Comment by czender** [comment]
I have not used cooley compute nodes in some time and now am unable to access your test environment/data. I sent @mark-petersen a request to add me to OceanClimate_2 to remediate that. In the meantime, please re-run the `ncclimo` command with `-d 1 `option so it prints the actual MPI commands that it uses and post the results here. It looks like `ncclimo` tries to use `mpirun -H` on cooley (and rhea) but clearly the conda `mpirun` does not support that option, and hopefully that is all that needs to be addressed. Surprised this has not arisen before but I think that's because the atmosphere folks are always using edison/cori for their hi-res MPI analyses.

**Comment by czender** [comment]
It appears that cooley mpirun now uses `-hosts` instead of `-H` for hostname option. I have changed to this format in the ncclimo/ncremap in the latest snapshot now in [bin,lib]_cooley. Please give that a whirl.

**Comment by xylar** [comment]
Thanks @czender, I'll rerun later this evening with the `-d` option.

**Comment by xylar** [comment]
Thanks @czender.  Do you know if that's true of both the native `mpirun` on `cooley` and the version form `conda`?

**Comment by czender** [comment]
Appears to be true for both :)

**Comment by xylar** [comment]
Okay, great!  That's convenient.

**Comment by xylar** [comment]
@czender, I was, indeed, able to run with this fix.  Thanks so much!

**Comment by xylar** [comment]
@darincomeau and @stephenprice, if you want to test using ncclimo with `mpi` parallelism, you just need to change:
```
ncclimoParallelMode = mpi
```
(this will work even without the fixes on this branch) and then modify your job script like this:
```
#!/bin/bash
#COBALT -t 1:00:00
#COBALT -n 2
#COBALT -A OceanClimate_2
source /lus/theta-fs0/projects/ccsm/acme/tools/e3sm-unified/base/etc/profile.d/conda.sh
conda activate mpas_analysis_1.2.2
export HDF5_USE_FILE_LOCKING=FALSE

export PATH=~zender/bin_cooley/:$PATH
...
```
Use more nodes if you need to, but 2 worked fine for me on a one-year test climatology.

**Comment by stephenprice** [comment]
Hi @xylar. Just to confirm, this is an entirely separate set of testing relative to that going on under [PR 553](https://github.com/MPAS-Dev/MPAS-Analysis/pull/553)?

**Comment by xylar** [comment]
> Just to confirm, this is an entirely separate set of testing relative to that going on under PR 553?

Correct, this is an alternative solution to #553

**Comment by stephenprice** [comment]
@xylar -- thanks. I will try this in a bit.

**Comment by xylar** [comment]
@stephenprice, again, could you approve when you get this to run successfully for you? I think I'll merge even though it doesn't work yet on cooley with the `conda` version of NCO.  The pieces are at least in place.

**Comment by stephenprice** [comment]
@xylar yes ... I will try to get it done this afternoon.

**Comment by czender** [comment]
@xylar If speed is a driving consideration, you might try ncclimo with MPI on 2,3,4,6,12 nodes. It scales well in my experience. n=2 solves the OOM issues, but does not really show how fast it can go. Also, would it be helpful to for me to cut a new NCO release that could be used with e3sm_unified?

**Comment by xylar** [comment]
@czender, again, I think running on more nodes just wastes those nodes for most of the time MPAS-Analysis is running (on only one node) so I don't think going to higher node counts really makes sense.  But if `ncclimo` is the bottleneck, we can try that as needed.  My understanding is that it still does thread parallelism per node, right?  So 2 nodes should run 6 threads on each node, right?

> Also, would it be helpful to for me to cut a new NCO release that could be used with e3sm_unified?

That would eventually be good but `e3sm_diags` and `processflow` are holding up a new release of E3SM-Unified right now so no need to rush a release of NCO right now.

**Comment by czender** [comment]
Yes, 2 nodes is the ideal choice to reduce idle nodes and to avoid OOM. 2 nodes will run 6 threads each.

**Pull request merged**
