### PR TITLE
Add new ocean climatology subtask for velocity

### PR DESCRIPTION
**Pull request by cbegeman**
Formerly, ocean velocity map plots were only supported in the context of comparison to SOSE data. The new task added by this PR allows climatology map plots of zonal velocity, meridional velocity, and velocity magnitude for any region, but comparison with observations is not yet supported.

### CODE REVIEW

**Comment by cbegeman** [comment]
Example results are available here: https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.cbegeman/analysis/v3.LR.abrupt-4xCO2_0101/velmag_31-36_v0/ocean/index.html

**Review by xylar — APPROVED** [review]
This looks amazing to me!  A really nice feature to have!

**Comment by xylar** [comment]
Oh, sorry, jumped the gun.  I'll re-review once there are docs.

**Review by xylar — APPROVED** [review]
The documentation looks good as well!

**Pull request merged**
