### PR TITLE
Adjust cartopy grid lines

### PR DESCRIPTION
**Pull request by xylar**
Switch from meridians every 60 to every 30 degrees.  Remove weird ticks on the vertical axes.

### CODE REVIEW

**Comment by xylar** [comment]
@milenaveneziani, I think you want this but wouldn't mind getting your approval (formally this time).

**Comment by milenaveneziani** [comment]
This was a great change in the paper figures.

**Review by milenaveneziani — APPROVED** [review]

**Comment by xylar** [comment]
## Testing

This was tested as part of an analysis test-suite run on Chrysalis:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/chrysalis/add_new_transects_to_transport_time_series/

**Comment by milenaveneziani** [comment]
This and the other merged PR's all look great, @xylar. Great enhancement to have for the next release.

**Comment by xylar** [comment]
Thanks @milenaveneziani!

**Pull request merged**
