### PR TITLE
Add more statistics to global climatology maps

### LINKED ISSUE #767: Add quantitative metrics to lat-lon plots
It would be useful to add some quantitative basic metrics to MPAS-Analysis lat-lon plots, such as for example:

- global mean (for model, obs)
- mean biais (for difference)
- RMSE  (for difference)
- correlation (for difference)

### PR DESCRIPTION
**Pull request by xylar**
The statistics are now in text boxes to the right, similar to E3SM_Diags.

closes #767

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

The chrysalis test results are here:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/add_more_climatology_stats/

Here is a typical plot:
image

**Comment by xylar** [comment]
This PR is based off of #770 and will need to wait for that one to be merged.  I'll probably rebase after that just to keep things a bit cleaner.

In the meantime, @golaz and @milenaveneziani, feel fee to comment on the example figure above.

**Comment by vanroekel** [comment]
@xylar thanks for doing this.  I think the sample image looks great!

**Comment by milenaveneziani** [comment]
This is great @xylar.

**Comment by xylar** [comment]
@vanroekel and @milenaveneziani, I'm going to take your comments as tacit reviews (since I still had the PR as a draft at the time).  I would like to have this in before the new release.

**Pull request merged**
