### PR TITLE
Switch simulationStartTime to xarray

### LINKED ISSUE #704: simulationStartTime not being read in
The following error is appearing, causing some (but not all) time series tasks to not run:

``` 
File "/global/project/projectdirs/m3412/dcomeau/mpas_analysis_repos/develop/MPAS-Analysis/mpas_analysis/shared/timekeeping/utility.py", line 64, in get_simulation_start_time
    simulationStartTime = ''.join(simulationStartTime.astype('U')).strip()
TypeError: sequence item 19: expected str instance, MaskedConstant found
```

The analysis is run off current ```develop``` (hash 3e700c2).

The simulations on which this occurs were branched off master on May 29, 2020 (E3SM hash ```be8d6eadf```, PR https://github.com/E3SM-Project/E3SM/pull/3526). The mpas-source hash is ```bdf772aa```; the latest ```ocean/develop``` merge into ```e3sm/develop``` for this hash is (https://github.com/MPAS-Dev/MPAS-Model/commit/9073cafe01e06d7b489656d40d72a905bec4dde2).

Perhaps overkill information, but I've been trying to track down recent changes that could point to the error.

tagging @stephenprice who has also seen this error.

### PR DESCRIPTION
**Pull request by xylar**
This should hopefully improve problems with string decoding

closes #704

### CODE REVIEW

**Comment by xylar** [comment]
@darincomeau, I haven't had a chance to fully test this but I *think* it will fix #704

**Comment by xylar** [comment]
@darincomeau, could you re-test with this branch?  I think it's finally fixed.  I'm running the analysis you pointed me to last week right now but it's at least getting through the initialization phase where it was going wrong before.

**Comment by darincomeau** [comment]
@xylar I'm now getting errors in all of the SOSE/WOCE transect tasks, e.g.:
```
analysis task soseTransects_plotJFM_lon_75.0_salinity failed during run
Traceback (most recent call last):
  File "/global/homes/d/dcomeau/miniconda3/envs/mpas-analysis/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 198, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/global/homes/d/dcomeau/miniconda3/envs/mpas-analysis/lib/python3.8/site-packages/xarray/backends/lru_cache.py", line 53, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/global/cscratch1/sd/dcomeau/e3sm_scratch/cori-knl/mpas-analysis-output/20200602.A_WCYCL1850-DIB-ISMF.ne30_SOwISC10to60E2r2.cori\
-knl/yrs1-10/clim/obs/remapped/SOSE_transects_5km_lon_75.0_uniform_10_to_1500m_at_10m.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', Fal\
se))]
```

**Comment by xylar** [comment]
@darincomeau, I didn't have any trouble with those.  I'm running with a pretty new `conda` environment.  Could you rebuild your conda environment (or create a new one) and see if that fixes this issue?  I wonder if `xarray` has maybe been updated to fix this issue?
```
conda config --add channels conda-forge
conda config --set channel_priority strict
conda create -n mpas-analysis python=3.8 numpy scipy "matplotlib-base>=3.0.2" \
    netCDF4 "xarray>=0.14.1" dask bottleneck lxml "nco>=4.8.1" pyproj \
    pillow cmocean progressbar2 requests setuptools shapely "cartopy>=0.18.0" \
    cartopy_offlinedata geometric_features gsw "pyremap<0.1.0"
    "mpas_tools>=0.0.8"
conda activate mpas-analysis
python -m mpas_analysis configs/polarRegions.conf config.20200602.A_WCYCL1850-DIB-ISMF.ne30_SOwISC10to60E2r2.cori-knl --generate=soseTransects
```

**Comment by xylar** [comment]
@darincomeau, I'm seeing a similar error when I run code that used to work fine  (ISMIP6 stuff) in an environment that used to work fine on files that have nothing to do with PIO2 and aren't new.  I'm not sure if this could be something specific to Cori, maybe a recent update or something?  I'm kind of baffled at the moment.

**Comment by xylar** [comment]
I see, in my case, it's just a very confusing "file not found" error.  Maybe the same for you and it will work if you purge and re-run?

**Comment by darincomeau** [comment]
Thanks @xylar - I had created a new environment last week before submitting this issue. I also tried clearing out the ```clim/obs``` directory to remove the troublesome files and running again (although not ``--purge`` to save time), and still got those errors. I'll try purging and running again.

**Comment by xylar** [comment]
@darincomeau, short of that, you are going to have to debug which file is missing and why.  The error message you posted doesn't give the offending file name so I would need that info to help you debug.

**Pull request merged**
