### PR TITLE
Clean up docstrings and documentaiton

### PR DESCRIPTION
**Pull request by xylar**
Just a simple clean-up PR.

### CODE REVIEW

**Comment by xylar** [comment]
Intended to finally address #100.

**Comment by xylar** [comment]
@milenaveneziani, depending on how much time you have, I'm looking for anything from a quick glance at the chances I made all the way to a thorough look at the documentation on the webpage (http://mpas-analysis.readthedocs.io/en/latest/?badge=latest) to see if you notice any obvious problems that I missed.

I'll merge this once you're happy.

**Comment by milenaveneziani** [comment]
I'm checking the doc link: the Index link works, but the Module Index doesn't, and the Search link doesn't seem to point to a search button.

**Comment by xylar** [comment]
Sorry @milenaveneziani, I didn't follow any of that.  I don't have any idea what you're referring to with "module index" or "search link".  If I go to the docs link, this is what I see:
image
If I enter something in the search box, it works fine for me.  If I go to any of the links, they work for me, too.  Are you building the docs yourself and having trouble there?

**Comment by xylar** [comment]
Ah, I see what you mean.  Module Index and Search Page at the bottom of the main page.  Indeed, they don't seem to work.  I'll look into it.

**Comment by xylar** [comment]
Thanks for noticing those.  The links should be gone now.

**Comment by milenaveneziani** [comment]
sorry, I don't see them gone.. I'm using this link:
`http://mpas-analysis.readthedocs.io/en/latest/?badge=latest#`

**Comment by xylar** [comment]
The docs online will only get updated after we merge this PR.  You have to build them yourself from this branch by going to docs and typing `make html`.

**Comment by xylar** [comment]
@milenaveneziani, if you're good with the changes so far, I'd like to merge this (or you can do so).  We can always do more clean up in the future but we won't be fully sure if this works or not until we merge the PR, unfortunately.  That's How ReadTheDocs works for now.

**Pull request merged**
