### PR TITLE
Remove old QU240 run, add new QU240wLI on edison

### PR DESCRIPTION
**Pull request by xylar**
This run is useful for quick tests of the full analysis.

### CODE REVIEW

**Comment by xylar** [comment]
@milenaveneziani, I ran a new short QU240wLI run so we have it around for running quick tests of the full analysis.  I'm going to copy it over to my laptop as well.

If you could run a full test (by just copying the example config file over and giving it an output directory) that would be great.  Maybe try out the new e3sm-unified v. 1.2.0 while you're at it (see instructions in my recent email to the e3sm list).

**Comment by xylar** [comment]
# Testing

Here is the output I see from running the full analysis on this run:
http://portal.nersc.gov/project/acme/xylar/20180514.G.oQU240wLI.edison/

Nailed it!  No need to run at higher res.

**Comment by milenaveneziani** [comment]
Hi @xylar: could you please change the group to the new mapping files? thanks.

**Comment by xylar** [comment]
Sorry about that.  Should now be fixed.

**Comment by milenaveneziani** [comment]
Retesting, but now I am getting python 2-3 kind errors:
```
Plotting 2-d maps of Sea ice thickness climatologies for FM against Observations (ICESat)...
analysis task climatologyMapSeaIceThickSH_plotFM failed during run
Traceback (most recent call last):
  File "/global/u2/m/milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/shared/analysis_task.py", line 317, in run
    self.run_task()
  File "/global/u2/m/milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/sea_ice/plot_climatology_map_subtask.py", line 313, in run_task
    modelOutput = remappedClimatology[self.mpasFieldName].values
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.0_py2.7_nox/lib/python2.7/site-packages/xarray/core/dataset.py", line 879, in __getitem__
    return self._construct_dataarray(key)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.0_py2.7_nox/lib/python2.7/site-packages/xarray/core/dataset.py", line 782, in _construct_dataarray
    self._variables, name, self._level_coords, self.dims)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.0_py2.7_nox/lib/python2.7/site-packages/xarray/core/dataset.py", line 72, in _get_virtual_variable
    ref_var = variables[ref_name]
KeyError: u'timeMonthly_avg_iceVolumeCell'
```
This is in the sea-ice as well as ocn climatologies (including OHC maps).

**Comment by xylar** [comment]
@milenaveneziani, I don't think that's a python2 vs. 3 error.  It seems like the variable name just isn't the expected one for some reason or it's missing from the file.  Could you try doing a `--purge` and see if it goes away?

**Comment by milenaveneziani** [comment]
good point. forgot to do that.

**Comment by xylar** [comment]
Great!  Thanks for testing.

**Pull request merged**
