### PR TITLE
Add ice shelves to global and sea-ice plots

### PR DESCRIPTION
**Pull request by xylar**
Before, ice shelves were not filled in in these plots.

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I ran this with my laptop (QU240wIS).  Below are one global and one sea-ice result for reference.  I think it takes care of this issue as discussed in #497.  The ice-shelf outlines are new but maybe unproblematic.

image

image

The ice-shelf features are now part of `cartopy_offlinedata` 0.2.3 so creating a new environment with that package on LANL IC should mean the plots work fine.

**Comment by xylar** [comment]
@milenaveneziani, for now no need to run any tests, just let me know if this looks okay.

**Comment by milenaveneziani** [comment]
That's nice! How about using a different gray (lighter?) for the ice shelf-to-land space? (if not too complicated..)

**Comment by xylar** [comment]
> How about using a different gray (lighter?) for the ice shelf-to-land space? 

No, that's quite easy.  (I would prefer a lighter gray or beige for all land, personally.) The only reason I didn't do this is because the ice shelves are not relevant features in the plots where they will now be accentuated.  But that's not a problem for me.

**Comment by xylar** [comment]
Also, by "the ice shelf-to-land space", do you mean the ice shelves? ;-)

**Comment by milenaveneziani** [comment]
> Also, by "the ice shelf-to-land space", do you mean the ice shelves? ;-)

yes ;)

**Comment by milenaveneziani** [comment]
@xylar: FYI, I found a bug with the --list option that has been introduced recently. I'll open an issue after the two meetings I have this afternoon. You can try it though and see  what you get, if you are curious.

**Comment by xylar** [comment]
I see what you mean.  I happened to do a `--list` earlier today and it worked fine but that was because I was giving it a config file.

**Comment by xylar** [comment]
I might have time to fix that tomorrow.  Shouldn't take long I hope.

**Pull request merged**
