### PR TITLE
Update default color maps

### PR DESCRIPTION
**Pull request by xylar**
Color maps for many analysis tasks have been updated, following a group discusion

### CODE REVIEW

**Comment by xylar** [comment]
This follows from the discussion in #388

**Comment by xylar** [comment]
To do a thorough testing, I based this branch off of #366, but since that branch isn't ready to merge yet, I may need to rebase back onto develop.

**Comment by xylar** [comment]
## Testing

Results with the new color maps are still running will appear here:
http://portal.nersc.gov/project/m2833/xylar/new_color_maps/20180209.GMPAS-IAF.T62_oEC60to30v3wLI.cori-knl.afterSalinityFix/

**Comment by milenaveneziani** [comment]
I like what I see so far. The `ice` colormap is better than I originally thought.

**Pull request merged**
