### PR TITLE
Add inset maps to transects and regional-mean plots

### LINKED ISSUE #390: Add an inset panel with a map to transect plots
The inset would show where the transect is located and would also indicate the start and end (e.g. with `A` and `A'`)

### PR DESCRIPTION
**Pull request by xylar**
This merge adds inset plots to:
* ocean transects
* ocean regional profiles
* ocean regional-mean time series
* Antarctic melt time series

Both time-series and vertical-section plotting functions have been modified to accommodate this functionality.  Files are no longer saved as part of these plotting functions, nor is the plot closed.  Instead, a function savefig has been added that is called later, possibly after adding an inset and/or making other alterations.  

Note: this PR adds `cartopy` and `geometric_features` as dependencies, and is thus no longer compatible with the latest E3SM-Unified (1.2.5).

I've tacked on a little bit of clean up to the documentation.

closes #390

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

So far, I have just run the 4 affected tasks on the QU240wLI run.  Here is the result:
https://portal.nersc.gov/project/m2833/xylar/test_insets/ocean/

Here is a typical time series plot:
image

Here is a typical transect:
image

Here is an example of a regional profile:
image

**Comment by xylar** [comment]
@milenaveneziani, @darincomeau, @matthewhoffman and others, I would very much like to know what you think and what improvements you would recommend.

**Comment by milenaveneziani** [comment]
Looks very good @xylar!

**Comment by darincomeau** [comment]
@xylar this looks great! This will be so nice to have for presentations.

**Comment by xylar** [comment]
I'm going to go ahead and merged this once my testing finishes.  If tweaks are desired later on (or issues emerge in testing), we can always make another pull request to address them.

**Pull request merged**
