### PR TITLE
Add enhancements and clean-up SOSE, Schmidtko and geojson tasks

### PR DESCRIPTION
**Pull request by xylar**
This merge adds various enhancements and performs clean-up related to the SOSE tasks:
* adding support for velocity and potential density to SOSE transects
* consolidating SOSE climatology maps into a single task
* Adding a config. option `fieldList` that determines which fields to plot
* Update docs to reflect these changes

The `fieldList` can be used to control with fields get plotted from either SOSE task. By default, all supported fields are plotted but if the user desires a subset, this is specified as, for example:
```
[soseTransects]
fieldList = ['temperature', 'salinity']
```

This merge also cleans up the Schmidtko  (for Antarctic bottom T, S and PD plots) and geojson transects tasks by converting the data structure used to specify information about each field from a dictionary (which can have random order) to a list (which has a fixed order).  Previously, galleries were added to the webpage by iterating through the dictionary, which meant that fields were sorted into an arbitrary order.  Now, they are in the order specified in the `fields` list.

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I tested this PR with the QU240wLI test on my laptop.  Running the 20180129.DECKv1b_piControl.ne30_oEC.edison test case on Edison right now and will post results here once it completes successfully.

**Comment by xylar** [comment]
@milenaveneziani, I am hoping to slip in this one last PR on my side before the v1.0 release.  We would benefit in the ALCC project from having these transect capabilities.

@gstreletz, I'm not sure if you have time or interest in reviewing this.  If so, please post a comment here so I know not to merge until you've tested and just give the branch a quick test.

**Comment by milenaveneziani** [comment]
sounds doable to me.

**Comment by xylar** [comment]
Thanks for taking a look, @gstreletz.

**Pull request merged**
