### PR TITLE
Various clean up

### PR DESCRIPTION
**Pull request by xylar**
Delete unneeded lock and simplify method for creating/reading mesh descriptors

### CODE REVIEW

**Comment by xylar** [comment]
@milenaveneziani, this PR is just some really minor clean up that's cluttering up another PR of mine.  If you could give it a quick look and maybe run a simple test, I'd be happy to merge it myself.

**Comment by milenaveneziani** [comment]
@xylar: do you understand why CI failed?

**Comment by xylar** [comment]
I'll fix it.  Sorry about that.

**Comment by xylar** [comment]
@milenaveneziani, I changed it so you can create or read in a mesh descriptor (the information needed to create a mapping file from a grid or mesh) with a simpler call.  I had forgotten to update CI to use the new syntax.  I've done so now.

**Comment by milenaveneziani** [comment]
@xylar: I did a quick test on edison. All goes well until the very end, when I get this:
```
Plotting sea-ice area and volume time series...

  Reading files:
    mpascice.hist.am.timeSeriesStatsMonthly.0049-01-01.nc through
    mpascice.hist.am.timeSeriesStatsMonthly.0050-12-01.nc
  Load sea-ice data...
   Caching NH data
   Read in previously computed time series
  Make NH plots...
   Caching SH data
   Read in previously computed time series
  Make SH plots...
Execution time: 0:00:25.00
Traceback (most recent call last):
  File "./run_analysis.py", line 401, in <module>
    run_analysis(config, analyses)
  File "./run_analysis.py", line 352, in run_analysis
    raise lastException
ValueError: arguments without labels along dimension u'nOceanRegionsTmp' cannot be aligned because they have different dimension sizes: set([1, 7])
```
Do you understand it?

**Comment by xylar** [comment]
@milenaveneziani, so I'll include a fix for the non-intuitive way that the error message was printed.  What it's doing is keeping the last exception that was raised by an earlier task and "re-raising" it so there's an error.  Instead, I'll have it print a more intuitive message like:
```
There were errors in 3 tasks: climatologyMapMLD, climatologyMapSST, climatologyMapSSS
The last stacktrace was:
Traceback (most recent call last):
  File "./run_analysis.py", line 340, in run_analysis
    analysisTask.run()
  File "/home/xylar/code/mpas-work/analysis/clean_up/mpas_analysis/ocean/climatology_map.py", line 112, in run
    crash
```

None of this says anything about the crash you saw, which I don't yet understand.

**Comment by milenaveneziani** [comment]
I can retry with the new commit and see what message I get.

**Comment by xylar** [comment]
The only place where `nOceanRegionsTmp` is used is in `timeSeriesOHC`.  Are you testing on one of the runs that we typically use for testing (with config files in `configs/edison`) or something else?  I'm testing now with the 2 cases in that directory to see if I get the same error.

**Comment by milenaveneziani** [comment]
indeed, OHC time series:
```
There were errors in task timeSeriesOHC
The stacktrace was:
Traceback (most recent call last):
  File "./run_analysis.py", line 340, in run_analysis
    analysisTask.run()
  File "/global/u2/m/milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/ocean/time_series_ohc.py", line 252, in run
    firstYearAvgLayerTemperature)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison_acme_unified_2017.9.13/lib/python2.7/site-packages/xarray/core/dataarray.py", line 1547, in func
    self, other = align(self, other, join=align_type, copy=False)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison_acme_unified_2017.9.13/lib/python2.7/site-packages/xarray/core/alignment.py", line 155, in align
    % (dim, sizes))
ValueError: arguments without labels along dimension u'nOceanRegionsTmp' cannot be aligned because they have different dimension sizes: set([1, 7])
```

**Comment by milenaveneziani** [comment]
I am testing with `20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG` on edison:
`~milena/MPAS-git-repositories/MPAS-Analysis/config.20170313.beta1.A_WCYCL1850S.ne30_oECv3_ICG.edison`

**Comment by xylar** [comment]
@milenaveneziani, so I can run successfully with `startYear=1` and `endYear=22` but I see your error when I set ``startYear=21` and `endYear=22`.

I would be surprised if this is a bug introduced by this branch.  Do you see the same error running on `develop`?

**Comment by xylar** [comment]
If so, I suggest we do a separate PR to fix this error.

**Comment by xylar** [comment]
Hmm, I'm wrong.  I runs fine on `develop`.  I'll keep looking into it...

**Comment by milenaveneziani** [comment]
not for me.. I get the same error on develop.

**Comment by milenaveneziani** [comment]
I don't understand how I could have missed it during all those tests for ncclimo.. Oh wait, maybe because I was asking to do climos only.

**Comment by milenaveneziani** [comment]
This commit, in fact, works (just prior to merging moc_with_ncclimo):
`e54b517 (HEAD) Merge remote-tracking branch 'xylar/MPAS-Analysis/remove_var_maps' into develop`

**Comment by xylar** [comment]
@milenaveneziani, I think I see the problem.  I'll do a separate PR to fix it.  I think the `remove_var_maps` branch was the one that introduce the bug.

**Comment by milenaveneziani** [comment]
hmm, but I don't see the error with that branch in..

**Comment by milenaveneziani** [comment]
So, do you think this one is ready to be merged?

**Comment by xylar** [comment]
@milenaveneziani, let's fix the bug in OHC first.  That way we can be sure this one isn't causing issues.  I should have a PR by the time you get in in the morning.

**Comment by xylar** [comment]
Since we aren't yet ready to merge #160, I have included two "clean-up" type commits from that branch here.  These move the `config.default` file into `mpas_analysis` and rename `run_analysis.py` to `run_mpas_analysis`.

I decided to include these changes so changes I'm currently making to `run_mpas_analysis` won't end up getting confused by the name change.

**Comment by xylar** [comment]
@milenaveneziani, could you do a test merge to develop and run the same test on this?  If it passes, I think we can merge this, too.  Should be no need to rebase, but I can if it makes your life easier.

**Comment by milenaveneziani** [comment]
@xylar: can this be merged since the OHC bug has been fixed? I will try a quick test first.

**Comment by milenaveneziani** [comment]
our messages crossed. give me a min.

**Comment by milenaveneziani** [comment]
I had to purge my project space a bit..
Test passed.
And I quite like that config.default is now in `mpas_analysis`. Makes for a much cleaner main directory.

**Comment by xylar** [comment]
> And I quite like that config.default is now in mpas_analysis. Makes for a much cleaner main directory.

I agree.  It has the added benefit that hopefully people won't try to modify it.  Of course, when we install MPAS-Analysis as a package, that will remove any temptation...

**Comment by xylar** [comment]
Thanks for getting both of these PRs merged so quickly!

**Pull request merged**
