### PR TITLE
Add climatology maps for OHC anomalies

### PR DESCRIPTION
**Pull request by xylar**
The maps show the OHC (per unit area) integrated over a list of depth ranges (by default 0 to 10,000 m, 0 to 700 m, 700 to 2000 m and 2000 to 10,000 m).  10,000 m is expected to be below the bottom of the ocean in all of our MPAS-O configurations.

### CODE REVIEW

**Comment by xylar** [comment]
Here is some example output from a low-res (QU240 km) run:

deltaohc_gmpas-qu240_ann_years0002-0005

**Comment by xylar** [comment]
Addresses #233

**Comment by xylar** [comment]
Similar to the plot above but for only 0-700 m depth:
deltaohc_gmpas-qu240_ann_years0002-0005

**Comment by milenaveneziani** [comment]
@xylar: this is great, thanks for adding this so quickly.

The only suggestion I have is to plot, by default, the depth ranges that we have for the integrated OHC: 0-700m, 700-2000m, 2000-bottom. This way we can compare the integrated curves with the maps. You could leave the option of adding an extra panel if `minDepth` and `maxDepth` are defined in the config file.
If you don't feel like doing this right now, we can merge it as is and then add the extra panels later.

**Comment by xylar** [comment]
@milenaveneziani, I don't think there's a rush to merge this PR and I do think what you suggest would be a great addition and relatively simple to implement.  I think it would be easier to do one remapping operation per vertical integral (rather than trying to do them all at once like we do with depths in the SOSE and Argo analysis).  This might be a tiny bit slower and will create more files but I think it'll be easier to implement.

**Comment by xylar** [comment]
@milenaveneziani, I added the requested feature.  Take a look here and let me know if you have further suggestions.
http://portal.nersc.gov/project/acme/xylar/ohc_clim_test/ocean/index.html

**Comment by xylar** [comment]
@maltrud or @vanroekel, do either of you have time to review this, just by taking a look at the plots in the link above?

**Comment by vanroekel** [comment]
@xylar I won't have time to review this well, so I've removed my name from the list.  Thanks for adding this feature!

**Pull request merged**
