### PR TITLE
Add periodic image to BGC obs data

### LINKED ISSUE #484: Fix periodic plot artifacts in BGC obs
image

Presumably the bug is because certain grids need to have a periodic copy of the last cell added on.

### PR DESCRIPTION
**Pull request by xylar**
This is needed to get expected plots in Antarctic projection

Note: mapping files will need to be replaced as part of fulfilling this PR.

closes #484

### CODE REVIEW

**Comment by xylar** [comment]
With this fix, the glitch seen in #484 is no longer visible:
image

**Comment by xylar** [comment]
@milenaveneziani, there would be one mapping file per BGC obs variable (one each for lat/lon and Antarctic comparison grids).  It looks like those mapping files are not on the public server in any case.   So we should include them on the server and add them to the download script as part of this PR.  

They are on LANL IC right now (and probably nowhere else) and they are:
```
map_obs_ALK_1.0x1.0degree_to_0.5x0.5degree_bilinear.nc
map_obs_ALK_1.0x1.0degree_to_6000.0x6000.0km_10.0km_Antarctic_stereo_bilinear.nc
map_obs_Chl_0.0833358764648x0.0833282470703degree_to_0.5x0.5degree_bilinear.nc
map_obs_Chl_0.0833358764648x0.0833282470703degree_to_6000.0x6000.0km_10.0km_Antarctic_stereo_bilinear.nc
map_obs_CO2_gas_flux_1.0x1.0degree_to_0.5x0.5degree_bilinear.nc
map_obs_CO2_gas_flux_1.0x1.0degree_to_6000.0x6000.0km_10.0km_Antarctic_stereo_bilinear.nc
map_obs_DIC_1.0x1.0degree_to_0.5x0.5degree_bilinear.nc
map_obs_DIC_1.0x1.0degree_to_6000.0x6000.0km_10.0km_Antarctic_stereo_bilinear.nc
map_obs_NO3_1.0x1.0degree_to_0.5x0.5degree_bilinear.nc
map_obs_NO3_1.0x1.0degree_to_6000.0x6000.0km_10.0km_Antarctic_stereo_bilinear.nc
map_obs_O2_1.0x1.0degree_to_0.5x0.5degree_bilinear.nc
map_obs_O2_1.0x1.0degree_to_6000.0x6000.0km_10.0km_Antarctic_stereo_bilinear.nc
map_obs_pH_3D_1.0x1.0degree_to_0.5x0.5degree_bilinear.nc
map_obs_pH_3D_1.0x1.0degree_to_6000.0x6000.0km_10.0km_Antarctic_stereo_bilinear.nc
map_obs_PO4_1.0x1.0degree_to_0.5x0.5degree_bilinear.nc
map_obs_PO4_1.0x1.0degree_to_6000.0x6000.0km_10.0km_Antarctic_stereo_bilinear.nc
map_obs_SiO3_1.0x1.0degree_to_0.5x0.5degree_bilinear.nc
map_obs_SiO3_1.0x1.0degree_to_6000.0x6000.0km_10.0km_Antarctic_stereo_bilinear.nc
```

**Comment by milenaveneziani** [comment]
great. thanks for clarifying.

**Comment by milenaveneziani** [comment]
Yes, as part of the release we should add a bullet about checking all obs and mapping files on all supported machines, as I am not 100% sure that everything is consistent everywhere.

**Comment by xylar** [comment]
Good idea. I'll add it.

**Comment by milenaveneziani** [comment]
done it already :)

**Pull request merged**
