### PR TITLE
Support multiple subprocesses per task (12 for ncclimo in bck mode)

### PR DESCRIPTION
**Pull request by xylar**
This requires each task to know how many subprocesses it has (1 for most tasks, 12 for ncclimo tasks).  In the future, tasks can also use `dask` or other methods to run multiple threads and the subprocess count can reflect this.

This should also prevent `ncclimo` from trying to run 12 threads while other tasks are running unless more than 12 parallel tasks are allowed via `parallelTaskCount`.

### CODE REVIEW

**Comment by xylar** [comment]
@stephenprice and @darincomeau, I'm going to make a conda environment on `cooley` so you can test this out (without the NCO problem you've seen in the past).  I'll ask you to test as soon as I have instructions.

**Comment by xylar** [comment]
@stephenprice and @darincomeau, if you load this python on cooley:
```
source /lus/theta-fs0/projects/ccsm/acme/tools/e3sm-unified/load_mpas_analysis.sh
```
then you should be able to run with this branch.  Could you try with an RRS30to10 analysis with `parallelTaskCount = 12` and `ncclimoParallelMode = bck`?  I think it should work now because it will run `ncclimo` tasks on their own, not overlapping any other tasks.  If you still run out of memory, there's no way around running `ncclimoParallelMode = serial` and I'll just need to see if we can use something other than `ncclimo` here in the future.

**Comment by darincomeau** [comment]
@xylar I still got the similar error I was seeing before:

Climatological monthly mean for month 11 ...
Climatological monthly mean for month 12 ...
ncclimo: ERROR monthly climo cmd_clm[7] failed. Debug this:
 ncra --cb -O --no_tmp_fl --fl_fmt=netcdf4 -v timeMonthly_avg_activeTracers_salinity,timeMonthly_avg_activeTracers_temperature,timeMonthly_avg_dThreshMLD,timeMonthly_avg_m
eridionalHeatTransportLat,timeMonthly_avg_meridionalHeatTransportLatZ,timeMonthly_avg_normalVelocity,timeMonthly_avg_potentialDensity,timeMonthly_avg_pressureAdjustedSSH,t
imeMonthly_avg_velocityMeridional,timeMonthly_avg_velocityZonal,timeMonthly_avg_vertVelocityTop --hdr_pad=10000 --gaa climo_script=ncclimo --gaa climo_command="'/lus/theta
-fs0/projects/ccsm/acme/tools/e3sm-unified/base/envs/e3sm_unified_1.2.4_py2.7_nox/bin/ncclimo -4 --clm_md=mth -a sdd -m mpaso -p bck -v timeMonthly_avg_activeTracers_salin
ity,timeMonthly_avg_activeTracers_temperature,timeMonthly_avg_dThreshMLD,timeMonthly_avg_meridionalHeatTransportLat,timeMonthly_avg_meridionalHeatTransportLatZ,timeMonthly
_avg_normalVelocity,timeMonthly_avg_potentialDensity,timeMonthly_avg_pressureAdjustedSSH,timeMonthly_avg_velocityMeridional,timeMonthly_avg_velocityZonal,timeMonthly_avg_v
ertVelocityTop --seasons=ANN,JAS,JFM -s 0001 -e 0001 -i /lus/theta-fs0/projects/OceanClimate_2/dcomeau/mpas-analysis-output/20190130.GMPAS-IAF.T62_oRRS30to10v3wLI.theta/cl
im/mpas/source_symlinks -o /lus/theta-fs0/projects/OceanClimate_2/dcomeau/mpas-analysis-output/20190130.GMPAS-IAF.T62_oRRS30to10v3wLI.theta/clim/mpas/unmasked_oRRS30to10v3
wLI'" --gaa climo_hostname=cooleylogin2 --gaa climo_version=4.7.8 --gaa yrs_averaged=0001 -p /lus/theta-fs0/projects/OceanClimate_2/dcomeau/mpas-analysis-output/20190130.G
MPAS-IAF.T62_oRRS30to10v3wLI.theta/clim/mpas/source_symlinks  mpaso.hist.am.timeSeriesStatsMonthly.0001-07-01.nc /lus/theta-fs0/projects/OceanClimate_2/dcomeau/mpas-analys
is-output/20190130.GMPAS-IAF.T62_oRRS30to10v3wLI.theta/clim/mpas/unmasked_oRRS30to10v3wLI/mpaso_07_000107_000107_climo.nc

/lus/theta-fs0/projects/ccsm/acme/tools/e3sm-unified/base/envs/e3sm_unified_1.2.4_py2.7_nox/bin/ncclimo: line 2264: 3996967 Killed

Curious if @stephenprice sees the same thing.

**Comment by xylar** [comment]
Okay, too bad!

**Comment by xylar** [comment]
I sent @zender a message to see if he might have some helpful hints.

**Comment by xylar** [comment]
## Testing

This worked fine on a QU240wLI test case (both python 2 and python 3) and main vs. control.  Although it didn't fix the problem on cooley, I think it should get merged in since it could give better performance in other cases.  It also fixes some glitches with newer package conflicts (bedmap and proj4) so those should get fixed in `develop` as soon as possible.

**Comment by czender** [comment]
Example MPI invocations for ncclimo on cooley compute nodes. nodecount should be a factor of 12 (1,2,3,4,6,12). It tells ncclimo how many nodes to divide the 12 months to compute simultaneously. nodecount = 4 means compute 3 months on each of four nodes simultaneously. 12 is fastest throughput = 1 month per node, thought that's probably excessive for med-res. simulations. Background mode that you are currently using means compute all 12 months simultaneously on one node, this is fine for lo-res but causes OOM on med or hi-res. Granularity of bck mode could be improved if requested, i.e., so fewer than 12 months simultaneously on one node, so it's more of a sliding scale between serial and full-on 12 months. This would require time to develop. For now, try MPI mode:

Interactive:
```
qsub -I -A HiRes_EarthSys --nodecount=12 --time=00:30:00 --jobname=ncclimo
ncclimo -d 1 -p mpi -c b1850c5_m2a -s 55 -e 58 -i /home/taylorm/scratch1.qtang/b1850c5_m2a/run -o ${DATA}/ne120/clm
```

Non-interactive:
```
echo '#!/bin/bash' > ~/ncclimo.cobalt
echo "ncclimo -d 1 -p mpi -c b1850c5_m2a -s 55 -e 58 -i /home/taylorm/scratch1.qtang/b1850c5_m2a/run -o ${DATA}/ne120/clm" >> ~/ncclimo.cobalt;chmod a+x ~/ncclimo.cobalt
qsub -A HiRes_EarthSys --nodecount=12 --time=00:30:00 --jobname ncclimo --error ~/ncclimo.err --output ~/ncclimo.out --notify zender@uci.edu ~/ncclimo.cobalt
```

**Comment by xylar** [comment]
Thanks @czender!  That's very helpful.  It does sound like a good solution is to start supporting `mpi` mode in MPAS-Analysis.  We hadn't had any need up to now but clearly we've hit that point.  At a glance, it's as simple as switching from `bck` to `mpi` and `ncclimo` automatically knows how many nodes are available.  Is that correct?

**Comment by xylar** [comment]
If we do that, most nodes will go to waste when ncclimo isn't running, which is kind of a shame and a shortfall of how MPAS-Analysis is currently implemented.

**Comment by czender** [comment]
Yes, and yes. Options to explore include my increasing granularity of -p bck mode. How much of MPAS-Analysis time is/isn't consumed by ncclimo?

**Comment by xylar** [comment]
> Options to explore include my increasing granularity of -p bck mode. 

That would be of interest to us but not a quick solution and we don't want you to put too much time into it.  The MPI option seems better other than the wasted resources, and that's a problem on our side, not yours.

> How much of MPAS-Analysis time is/isn't consumed by ncclimo?

If we run in `bck` mode (and presumably `mpi`), `ncclimo` takes only a small fraction of the total run time.  So there would be some major node idling but we can afford that as long as queue time isn't a bit deal.  In a real pinch, we could run `ncclimo` first on multiple nodes and MPAS-Analysis after on one node (like I think `e3sm_diags` does) but I'd really prefer not to have that added complexity for users.

**Pull request merged**
