### PR TITLE
Add design document for climatology classes

### PR DESCRIPTION
**Pull request by xylar**
A design document describing the transition from functions to classes in the `climatology` module.

### CODE REVIEW

**Comment by milenaveneziani** [comment]
I think we should review this and #206, #209 next, right?

**Comment by xylar** [comment]
Yes, that's right.  I won't have much time to respond because I'm at a meeting over the next 3 days but would appreciate your comments whenever you have time.

**Comment by milenaveneziani** [comment]
Hi @xylar: sorry for the delay on this, I came back from vacation yesterday.
Unfortunately I don't have enough time to go into the details of this. My main concern, as usual, is whether this implementation would cause a significant increase in complexity, making it harder for a potential contributor to actually contribute with new analysis scripts.
@pwolfram: I know you are also busy with other things, but do you have any general comments or major concerns?

**Comment by milenaveneziani** [comment]
I see now that this PR and #206, #209 are meant to explain the changes made in #204.

**Comment by milenaveneziani** [comment]
ok, I went through the 3 design documents (fairly quickly) and now I understand the ideas and motivation for these. It is, though, a bit too high-level python for me to grasp fully, so I would suggest for @pwolfram and @vanroekel to take a look too when they get a chance (otherwise these design documents are a bit wasted.. :).
One quick question: did you test the pre-requisite tasks in batch mode as well?

**Comment by xylar** [comment]
@milenaveneziani, yes, I did check the prerequisite tasks with parallel tasks as well.  That's actually a major cause of the complexity of prerequisite tasks.  A given task can only be launched when its prerequisites are completed and that is obviously more complicated to keep track of with parallel tasks.

**Comment by xylar** [comment]
> My main concern, as usual, is whether this implementation would cause a significant increase in complexity, making it harder for a potential contributor to actually contribute with new analysis scripts.

I'm always interested in getting feedback on simpler alternatives to the approaches I've taken.  I think we need to figure out how to make it easier to make contributions to this repo, though, given that I seem to be the only person with significant time to put into its development and there isn't even enough time to review my PRs or design documents.

**Comment by xylar** [comment]
We are probably not going to go with this design solution.

**Pull request closed without merging**
