### PR TITLE
Fix bounds on sea-ice time series from cache file

### PR DESCRIPTION
**Pull request by xylar**
The bounds were previously being ignored and the full time range was being loaded, which is not the correct behavior if he time bounds have been diminished.

### CODE REVIEW

**Comment by xylar** [comment]
This is intended to address #364

**Comment by xylar** [comment]
## Testing
I ran with a QU240 test case once on years 1 to 5 and again (without purging) on years 1 to 3, and saw the expected behavior: In the first run, the plot extended to year 5, and in the second run, the plot extended only to year 3.

**Comment by milenaveneziani** [comment]
maybe another python 2 issue:
```
Traceback (most recent call last):
  File "./run_mpas_analysis", line 553, in <module>
    analyses = build_analysis_list(config, refConfig)
  File "./run_mpas_analysis", line 87, in build_analysis_list
    config=config,  componentName='ocean')
  File "/global/u2/m/milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/shared/climatology/ref_year_mpas_climatology_task.py", line 66, in __init__
    config.write(config_string)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison_e3sm_unified_1.1.3_py2_nox/lib/python2.7/ConfigParser.py", line 407, in write
    fp.write("[%s]\n" % section)
TypeError: unicode argument expected, got 'str'
```

**Comment by xylar** [comment]
Actually, the same python2 error as before.  I need to rebase onto develop.  Sorry about that...

**Comment by xylar** [comment]
@milenaveneziani, please do a hard reset and try again.  Thanks!

**Comment by milenaveneziani** [comment]
@xylar: have you run your test with MOC on?

I have run a 1-10 year test with no problems, then I re-run without purging and asking for time series from year 1 to 5. I am getting this unusual error when doing the MOC timeseries (only error I got):
```
  Compute and/or plot post-processed Atlantic MOC time series...
   Load data...
   Read in previously computed MOC time series
analysis task streamfunctionMOC failed during run
Traceback (most recent call last):
  File "/global/u2/m/milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/shared/analysis_task.py", line 317, in run
    self.run_task()
  File "/global/u2/m/milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/ocean/streamfunction_moc.py", line 189, in run_task
    dsMOCTimeSeries = self._compute_moc_time_series_postprocess()
  File "/global/u2/m/milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/ocean/streamfunction_moc.py", line 538, in _compute_moc_time_series_postprocess
    outIndex = np.where(mask)[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by milenaveneziani** [comment]
I have looked at the times in the mocTimeseries file and they go from ~15 to ~3600, as expected.

**Comment by xylar** [comment]
@milenaveneziani, I'm able to reproduce the MOC error you saw.  Although it's kind of beyond the original scope of the PR, I'm happy to look into it and probably fix it here.

**Comment by xylar** [comment]
Okay, I think I've fixed both issues.  For the sea ice time series, I decided to do the same thing we're doing on the ocean side, which is not trying to reuse the individual time series files at all but rather recomputing them from scratch when we re-run.  We *do* reuse the time series cache for the MOC but that's because it's so expensive to compute.

@milenaveneziani, if you could run one last test, I'll merge when you're happy with my latest changes.

**Comment by milenaveneziani** [comment]
sorry for the delay. I just ran a test for years 1-3 and all worked.
Thanks @xylar!

**Pull request merged**
