### PR TITLE
Optionally compute climatologies with xarray/dask

### PR DESCRIPTION
**Pull request by xylar**
...instead of `ncclimo`.

The files produced with `xarray`/`dask` drop the `Time` dimension so various subsequent calls that drop the time dimension are no longer needed (except when `ncclimo` is still used).

set the config option
```
[climatology]
useNcclimo = False
```
to use xarray for climatologies.

This PR also reorganizes the way the SOSE transects are preprocessed (so that mapping files can be created for interpolating them).  With the reorganization, preprocessing is faster and uses significantly less memory.

### CODE REVIEW

**Comment by xylar** [comment]
@stephenprice and @darincomeau, could you test out this branch on cooley when you get a chance?  You will need to set the config option above and use the conda environment I created:
```
source /lus/theta-fs0/projects/ccsm/acme/tools/e3sm-unified/load_mpas_analysis.sh
```
instead of E3SM-Unified.

**Comment by milenaveneziani** [comment]
Hi @xylar, may I ask the advantage of using this instead of ncclimo?

**Comment by xylar** [comment]
@milenaveneziani, this is a little faster in my tests but more importantly it's more flexible with the amount of memory we use, whereas `ncclimo` seems to be running out of memory for us on cooley (despite 300+GB of ram on the compute nodes!?).

**Comment by milenaveneziani** [comment]
hmm, I have run on cooley fairly often lately, with the high-res data, and didn't run into memory problems. perhaps I was lucky. I was running in serial on one compute node.

**Comment by xylar** [comment]
Right, the problem is that running in `serial` takes 12 times as long, which is really frustrating for 10-year climatologies.  We're hoping for some what around that.

**Comment by milenaveneziani** [comment]
Actually the part that takes the longest (as a heads-up), especially at high-res, is the computation (time series generation) behind the ocean basin stratification plots. They are nice to have for sure, but they are very time consuming.

**Comment by xylar** [comment]
> Actually the part that takes the longest (as a heads-up), especially at high-res, is the computation (time series generation) behind the ocean basin stratification plots.

Oh, okay.  I'm surprised to hear that.  I'll look into optimizing those, too.

**Comment by xylar** [comment]
How many parallel tasks are you running with?

**Comment by milenaveneziani** [comment]
only one.. not a good idea I guess..

**Comment by milenaveneziani** [comment]
The script I have been using is this:
`~milena/MPAS-git-repositories/MPAS-Analysis/job_script.cooley.bash`

**Comment by xylar** [comment]
I'd try running with 12 parallel tasks even if you have to run ncclimo in serial mode.  If 12 is too many, cut down but I wouldn't got down to 1.  The analysis just has way too many parts to try to run in serial.

The only solution for cooley may be to figure out how to run on multiple nodes.  12 cores per node isn't a lot, especially for high res.

**Comment by milenaveneziani** [comment]
ok, will try that next time.

**Comment by xylar** [comment]
## Testing

This failed one test (QU240) on cori related to the sea ice climatology. I'll need to check to make sure I was running with the right version of the branch and fix the issue if so.

I plan to test on an EC60to30 run on cori and then on an RRS30to10 run on cooley.  Others are welcome to test this but I think it's still a work in progress.

**Comment by xylar** [comment]
Okay @stephenprice and @darincomeau, this is ready for you to try out if you want.  Again, all you have to do is try:
```
[climatology]
useNcclimo = False
```
In your job script, make sure to do this instead of loading e3sm-unified (wrong NCO version):
```
source /lus/theta-fs0/projects/ccsm/acme/tools/e3sm-unified/load_mpas_analysis.sh
```
You should be able to run with 12 parallel tasks without running out of memory.  This bypasses ncclimo so no need to worry about which mode ncclimo parallelism is in.

**Comment by stephenprice** [comment]
@xylar -- I'll go back and look again to make sure I didn't mess something up, but my first try resulted in a bunch of errors saying "Disk quota exceeded". Let me get the analysis for the final year of those three param sens runs complete and posted first and then I'll come back to this.

**Comment by xylar** [comment]
@stephenprice, I think it's very likely you did exceed your disk quota.  Best to check on that.

**Comment by stephenprice** [comment]
@xylar , @darincomeau -- any idea where I can find out what the disk quota is on Cooley? It could be that the 18to6 analysis was using up a big chunk of my space (If we are limited to 1 Tb).

**Comment by xylar** [comment]
@stephenprice, you should be doing your analysis in the OceanClimate_2 space: `/lus/theta-fs0/projects/OceanClimate_2/`
If your analysis isn't there, I'm not sure what your quota is but it wouldn't be surprising if you're out of space.

**Comment by darincomeau** [comment]
On Cooley I see:

-bash-4.2$ myprojectquotas

mira-fs0 : Current Project Quota information for projects you're a member of:

Name                           Type     Filesystem        GB_Used       GB_Quota          Grace
===============================================================================================
OceanClimate_2              Project       mira-fs0         719.19        1000.00           none

So we are getting close to the 1TB limit.

**Comment by stephenprice** [comment]
Thanks @xylar and @darincomeau. I'll try that. I didn't know that the project space _on_ Cooley was not useful.

**Comment by xylar** [comment]
> I didn't know that the project space on Cooley was not useful.

I think that's correct.

**Comment by stephenprice** [comment]
@xylar -- for analysis of a single year of data, would you expect these warnings? I don't remember seeing them when we confirmed a recent version of the analysis working on a single year of output.

Warning: timeSeriesTemperatureAnomaly: computeAnomaly failed during check and will not be run
Warning: subtask of timeSeriesTemperatureAnomaly failed during check, so this task will not be run
Warning: timeSeriesSalinityAnomaly: computeAnomaly failed during check and will not be run
Warning: subtask of timeSeriesSalinityAnomaly failed during check, so this task will not be run
Warning: timeSeriesOHCAnomaly: computeAnomaly failed during check and will not be run
Warning: subtask of timeSeriesOHCAnomaly failed during check, so this task will not be run
Warning: indexNino34 failed during check and will not be run

**Comment by darincomeau** [comment]
@stephenprice yes those are expected errors when running on one year of data. @xylar put this in #547 .

**Comment by darincomeau** [comment]
@xylar I'm getting an error in the mpasClimatologyOcean task:
ERROR in task mpasClimatologyOcean: JAS.  See log file /lus/theta-fs0/projects/OceanClimate_2/dcomeau/mpas-analysis-output/20190130.GMPAS-IAF.T62_oRRS30to10v3wLI.theta/logs/mpasClimatologyOcean_JAS.log for details
Running tasks:  77% |########################################################################################                          | ETA:   0:00:06ERROR in task mpasClimatologyOcean: ANN.  See log file /lus/theta-fs0/projects/OceanClimate_2/dcomeau/mpas-analysis-output/20190130.GMPAS-IAF.T62_oRRS30to10v3wLI.theta/logs/mpasClimatologyOcean_ANN.log for details

From the bottom of the error logs:
ValueError: arguments without labels along dimension u'Time' cannot be aligned because they have different dimension sizes: set([0, 1])

**Comment by stephenprice** [comment]
Thanks @darincomeau. I'll let you know if I see your error above when I get that far. Just calculating the monthlies right now ...

**Comment by stephenprice** [comment]
I got a single year of the 30to10 analysis to complete successfully using this hash. It's [here](http://portal.nersc.gov/project/m2833/mpas_analysis_output/20190301.GMPAS-DIB-IAF-ISMF.T62_oRRS30to10v3wLI.theta/).

**Comment by stephenprice** [comment]
@xylar -- this has now worked fine for me for 3 diff. (short , 1 yr) 30to10 analyses.

**Comment by xylar** [comment]
@darincomeau, yes, this might not work if you run once with `useNcclimo = True` (i.e. the old code) and once with `useNcclimo = False` without purging.  I don't think I consider it a bug if that doesn't work.  That's just not a good idea.  Would you agree that you wouldn't normally try that?

It *should* work to run the code twice without changing `useNcclimo` so I hope that's not what went wrong for you.

**Comment by xylar** [comment]
@stephenprice, could you approve the PR if you're happy?

**Comment by darincomeau** [comment]
>  I don't think I consider it a bug if that doesn't work. That's just not a good idea. Would you agree that you wouldn't normally try that?

Agreed - I considered my mistake user error, and realized it wasn't a good idea to run without ```--purge``` in this case, since I had previously run the analysis using ```ncclimo```.

**Pull request merged**
