### PR TITLE
Check for requested variables in timeSeriesStatsMonthly

### PR DESCRIPTION
**Pull request by xylar**
Before calling NCO tools, raise exceptions if the requested variables are not available so only tasks requesting unavailable variables fail, not the full analysis.

### CODE REVIEW

**Comment by xylar** [comment]
##Testing

I tested this on the QU240 G case output I typically use for testing.  Since this output doesn't have the `pressureAdjustedSSH` output, including the task for plotting the SSH would previously cause all analysis to fail as described in #328.  With this merge, only the `climatologyMapSSH` task fails during the `setup_and_check` phase and other analysis continues as expected.  The error message is:
```
Traceback (most recent call last):
  File "./run_mpas_analysis", line 250, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/home/xylar/code/mpas-work/analysis/check_missing_variables/mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py", line 201, in setup_and_check
    self.mpasClimatologyTask.add_variables(self.variableList, self.seasons)
  File "/home/xylar/code/mpas-work/analysis/check_missing_variables/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 155, in add_variables
    'output:\n{}'.format(variable, self.allVariables))
ValueError: timeMonthly_avg_pressureAdjustedSSH is not available in  timeSeriesStatsMonthly output:
['timeMonthly_counter', 'xtime_startMonthly', 'xtime_endMonthly', 'timeMonthly_avg_daysSinceStartOfSim', 'timeMonthly_avg_ssh', 'timeMonthly_avg_velocityMeridional', 'timeMonthly_avg_velocityZonal', 'timeMonthly_avg_layerThickness', 'timeMonthly_avg_windStressZonal', 'timeMonthly_avg_windStressMeridional', 'timeMonthly_avg_frazilLayerThicknessTendency', 'timeMonthly_avg_meridionalHeatTransportLatZ', 'timeMonthly_avg_meridionalHeatTransportLat', 'timeMonthly_avg_tThreshMLD', 'timeMonthly_avg_dThreshMLD', 'timeMonthly_avg_tGradMLD', 'timeMonthly_avg_dGradMLD', 'timeMonthly_avg_normalVelocity', 'timeMonthly_avg_vertVelocityTop', 'timeMonthly_avg_normalTransportVelocity', 'timeMonthly_avg_vertTransportVelocityTop', 'timeMonthly_avg_normalGMBolusVelocity', 'timeMonthly_avg_vertGMBolusVelocityTop', 'timeMonthly_avg_penetrativeTemperatureFlux', 'timeMonthly_avg_latentHeatFlux', 'timeMonthly_avg_sensibleHeatFlux', 'timeMonthly_avg_longWaveHeatFluxUp', 'timeMonthly_avg_longWaveHeatFluxDown', 'timeMonthly_avg_seaIceHeatFlux', 'timeMonthly_avg_shortWaveHeatFlux', 'timeMonthly_avg_evaporationFlux', 'timeMonthly_avg_seaIceSalinityFlux', 'timeMonthly_avg_seaIceFreshWaterFlux', 'timeMonthly_avg_riverRunoffFlux', 'timeMonthly_avg_iceRunoffFlux', 'timeMonthly_avg_rainFlux', 'timeMonthly_avg_snowFlux', 'timeMonthly_avg_activeTracers_temperature', 'timeMonthly_avg_activeTracers_salinity', 'timeMonthly_avg_avgValueWithinOceanRegion_sumSurfaceMaskValue', 'timeMonthly_avg_avgValueWithinOceanRegion_avgSurfaceArea', 'timeMonthly_avg_avgValueWithinOceanRegion_avgLatentHeatFlux', 'timeMonthly_avg_avgValueWithinOceanRegion_avgSensibleHeatFlux', 'timeMonthly_avg_avgValueWithinOceanRegion_avgLongWaveHeatFluxUp', 'timeMonthly_avg_avgValueWithinOceanRegion_avgLongWaveHeatFluxDown', 'timeMonthly_avg_avgValueWithinOceanRegion_avgSeaIceHeatFlux', 'timeMonthly_avg_avgValueWithinOceanRegion_avgShortWaveHeatFlux', 'timeMonthly_avg_avgValueWithinOceanRegion_avgEvaporationFlux', 'timeMonthly_avg_avgValueWithinOceanRegion_avgSeaIceFreshWaterFlux', 'timeMonthly_avg_avgValueWithinOceanRegion_avgRiverRunoffFlux', 'timeMonthly_avg_avgValueWithinOceanRegion_avgIceRunoffFlux', 'timeMonthly_avg_avgValueWithinOceanRegion_avgRainFlux', 'timeMonthly_avg_avgValueWithinOceanRegion_avgSnowFlux', 'timeMonthly_avg_avgValueWithinOceanRegion_avgSeaIceEnergy', 'timeMonthly_avg_avgValueWithinOceanRegion_avgSurfaceThicknessFlux', 'timeMonthly_avg_avgValueWithinOceanRegion_avgSurfaceTemperatureFlux', 'timeMonthly_avg_avgValueWithinOceanRegion_avgSurfaceSalinityFlux', 'timeMonthly_avg_avgValueWithinOceanRegion_avgSeaIceSalinityFlux', 'timeMonthly_avg_avgValueWithinOceanRegion_avgSurfaceWindStressMagnitude', 'timeMonthly_avg_avgValueWithinOceanRegion_avgWindStressZonal', 'timeMonthly_avg_avgValueWithinOceanRegion_avgWindStressMeridional', 'timeMonthly_avg_avgValueWithinOceanRegion_avgSeaSurfacePressure', 'timeMonthly_avg_avgValueWithinOceanRegion_avgSurfaceSSH', 'timeMonthly_avg_avgValueWithinOceanRegion_avgSurfaceTemperature', 'timeMonthly_avg_avgValueWithinOceanRegion_avgSurfaceSalinity', 'timeMonthly_avg_avgValueWithinOceanRegion_avgBoundaryLayerDepth', 'timeMonthly_avg_avgValueWithinOceanRegion_avgSurfaceNetHeatFlux', 'timeMonthly_avg_avgValueWithinOceanRegion_avgSurfaceNetSalinitFlux', 'timeMonthly_avg_avgValueWithinOceanRegion_avgSurfaceNetFreshWaterFlux', 'timeMonthly_avg_avgValueWithinOceanLayerRegion_sumLayerMaskValue', 'timeMonthly_avg_avgValueWithinOceanLayerRegion_avgLayerArea', 'timeMonthly_avg_avgValueWithinOceanLayerRegion_avgLayerThickness', 'timeMonthly_avg_avgValueWithinOceanLayerRegion_avgLayerDensity', 'timeMonthly_avg_avgValueWithinOceanLayerRegion_avgLayerPotentialDensity', 'timeMonthly_avg_avgValueWithinOceanLayerRegion_avgLayerBruntVaisalaFreqTop', 'timeMonthly_avg_avgValueWithinOceanLayerRegion_avgLayerVelocityZonal', 'timeMonthly_avg_avgValueWithinOceanLayerRegion_avgLayerVelocityMeridional', 'timeMonthly_avg_avgValueWithinOceanLayerRegion_avgLayerVertVelocityTop', 'timeMonthly_avg_avgValueWithinOceanLayerRegion_avgLayerTemperature', 'timeMonthly_avg_avgValueWithinOceanLayerRegion_avgLayerSalinity', 'timeMonthly_avg_avgValueWithinOceanLayerRegion_avgLayerKineticEnergyCell', 'timeMonthly_avg_avgValueWithinOceanLayerRegion_avgLayerRelativeVorticityCell', 'timeMonthly_avg_avgValueWithinOceanLayerRegion_avgLayerDivergence', 'timeMonthly_avg_avgValueWithinOceanLayerRegion_avgLayerRelativeEnstrophyCell', 'timeMonthly_avg_avgValueWithinOceanVolumeRegion_sumVolumeMaskValue', 'timeMonthly_avg_avgValueWithinOceanVolumeRegion_avgVolumeArea', 'timeMonthly_avg_avgValueWithinOceanVolumeRegion_avgVolumeThickness', 'timeMonthly_avg_avgValueWithinOceanVolumeRegion_avgVolumeDensity', 'timeMonthly_avg_avgValueWithinOceanVolumeRegion_avgVolumePotentialDensity', 'timeMonthly_avg_avgValueWithinOceanVolumeRegion_avgVolumeBruntVaisalaFreqTop', 'timeMonthly_avg_avgValueWithinOceanVolumeRegion_avgVolumeVelocityZonal', 'timeMonthly_avg_avgValueWithinOceanVolumeRegion_avgVolumeVelocityMeridional', 'timeMonthly_avg_avgValueWithinOceanVolumeRegion_avgVolumeVertVelocityTop', 'timeMonthly_avg_avgValueWithinOceanVolumeRegion_avgVolumeTemperature', 'timeMonthly_avg_avgValueWithinOceanVolumeRegion_avgVolumeSalinity', 'timeMonthly_avg_avgValueWithinOceanVolumeRegion_avgVolumeKineticEnergyCell', 'timeMonthly_avg_avgValueWithinOceanVolumeRegion_avgVolumeRelativeVorticityCell', 'timeMonthly_avg_avgValueWithinOceanVolumeRegion_avgVolumeDivergence', 'timeMonthly_avg_avgValueWithinOceanVolumeRegion_avgVolumeRelativeEnstrophyCell', 'timeMonthly_avg_minGlobalStats_layerThicknessMin', 'timeMonthly_avg_minGlobalStats_normalVelocityMin', 'timeMonthly_avg_minGlobalStats_tangentialVelocityMin', 'timeMonthly_avg_minGlobalStats_layerThicknessEdgeMin', 'timeMonthly_avg_minGlobalStats_relativeVorticityMin', 'timeMonthly_avg_minGlobalStats_enstrophyMin', 'timeMonthly_avg_minGlobalStats_kineticEnergyCellMin', 'timeMonthly_avg_minGlobalStats_normalizedAbsoluteVorticityMin', 'timeMonthly_avg_minGlobalStats_pressureMin', 'timeMonthly_avg_minGlobalStats_montgomeryPotentialMin', 'timeMonthly_avg_minGlobalStats_vertVelocityTopMin', 'timeMonthly_avg_minGlobalStats_vertAleTransportTopMin', 'timeMonthly_avg_minGlobalStats_lowFreqDivergenceMin', 'timeMonthly_avg_minGlobalStats_highFreqThicknessMin', 'timeMonthly_avg_minGlobalStats_temperatureMin', 'timeMonthly_avg_minGlobalStats_salinityMin', 'timeMonthly_avg_minGlobalStats_layerThicknessPreviousTimestepMin', 'timeMonthly_avg_minGlobalStats_frazilLayerThicknessTendencyMin', 'timeMonthly_avg_minGlobalStats_evaporationFluxMin', 'timeMonthly_avg_minGlobalStats_rainFluxMin', 'timeMonthly_avg_minGlobalStats_snowFluxMin', 'timeMonthly_avg_minGlobalStats_seaIceFreshWaterFluxMin', 'timeMonthly_avg_minGlobalStats_riverRunoffFluxMin', 'timeMonthly_avg_minGlobalStats_iceRunoffFluxMin', 'timeMonthly_avg_minGlobalStats_temperatureFluxMin', 'timeMonthly_avg_minGlobalStats_salinityFluxMin', 'timeMonthly_avg_minGlobalStats_salinityRestoringFluxMin', 'timeMonthly_avg_minGlobalStats_landIceFreshwaterFluxMin', 'timeMonthly_avg_minGlobalStats_accumulatedLandIceMassMin', 'timeMonthly_avg_minGlobalStats_accumulatedLandIceHeatMin', 'timeMonthly_avg_minGlobalStats_accumulatedLandIceFrazilMassMin', 'timeMonthly_avg_maxGlobalStats_layerThicknessMax', 'timeMonthly_avg_maxGlobalStats_normalVelocityMax', 'timeMonthly_avg_maxGlobalStats_tangentialVelocityMax', 'timeMonthly_avg_maxGlobalStats_layerThicknessEdgeMax', 'timeMonthly_avg_maxGlobalStats_relativeVorticityMax', 'timeMonthly_avg_maxGlobalStats_enstrophyMax', 'timeMonthly_avg_maxGlobalStats_kineticEnergyCellMax', 'timeMonthly_avg_maxGlobalStats_normalizedAbsoluteVorticityMax', 'timeMonthly_avg_maxGlobalStats_pressureMax', 'timeMonthly_avg_maxGlobalStats_montgomeryPotentialMax', 'timeMonthly_avg_maxGlobalStats_vertVelocityTopMax', 'timeMonthly_avg_maxGlobalStats_vertAleTransportTopMax', 'timeMonthly_avg_maxGlobalStats_lowFreqDivergenceMax', 'timeMonthly_avg_maxGlobalStats_highFreqThicknessMax', 'timeMonthly_avg_maxGlobalStats_temperatureMax', 'timeMonthly_avg_maxGlobalStats_salinityMax', 'timeMonthly_avg_maxGlobalStats_layerThicknessPreviousTimestepMax', 'timeMonthly_avg_maxGlobalStats_frazilLayerThicknessTendencyMax', 'timeMonthly_avg_maxGlobalStats_evaporationFluxMax', 'timeMonthly_avg_maxGlobalStats_rainFluxMax', 'timeMonthly_avg_maxGlobalStats_snowFluxMax', 'timeMonthly_avg_maxGlobalStats_seaIceFreshWaterFluxMax', 'timeMonthly_avg_maxGlobalStats_riverRunoffFluxMax', 'timeMonthly_avg_maxGlobalStats_iceRunoffFluxMax', 'timeMonthly_avg_maxGlobalStats_temperatureFluxMax', 'timeMonthly_avg_maxGlobalStats_salinityFluxMax', 'timeMonthly_avg_maxGlobalStats_salinityRestoringFluxMax', 'timeMonthly_avg_maxGlobalStats_landIceFreshwaterFluxMax', 'timeMonthly_avg_maxGlobalStats_accumulatedLandIceMassMax', 'timeMonthly_avg_maxGlobalStats_accumulatedLandIceHeatMax', 'timeMonthly_avg_maxGlobalStats_accumulatedLandIceFrazilMassMax', 'timeMonthly_avg_sumGlobalStats_layerThicknessSum', 'timeMonthly_avg_sumGlobalStats_normalVelocitySum', 'timeMonthly_avg_sumGlobalStats_tangentialVelocitySum', 'timeMonthly_avg_sumGlobalStats_layerThicknessEdgeSum', 'timeMonthly_avg_sumGlobalStats_relativeVorticitySum', 'timeMonthly_avg_sumGlobalStats_enstrophySum', 'timeMonthly_avg_sumGlobalStats_kineticEnergyCellSum', 'timeMonthly_avg_sumGlobalStats_normalizedAbsoluteVorticitySum', 'timeMonthly_avg_sumGlobalStats_pressureSum', 'timeMonthly_avg_sumGlobalStats_montgomeryPotentialSum', 'timeMonthly_avg_sumGlobalStats_vertVelocityTopSum', 'timeMonthly_avg_sumGlobalStats_vertAleTransportTopSum', 'timeMonthly_avg_sumGlobalStats_lowFreqDivergenceSum', 'timeMonthly_avg_sumGlobalStats_highFreqThicknessSum', 'timeMonthly_avg_sumGlobalStats_temperatureSum', 'timeMonthly_avg_sumGlobalStats_salinitySum', 'timeMonthly_avg_sumGlobalStats_layerThicknessPreviousTimestepSum', 'timeMonthly_avg_sumGlobalStats_frazilLayerThicknessTendencySum', 'timeMonthly_avg_sumGlobalStats_evaporationFluxSum', 'timeMonthly_avg_sumGlobalStats_rainFluxSum', 'timeMonthly_avg_sumGlobalStats_snowFluxSum', 'timeMonthly_avg_sumGlobalStats_seaIceFreshWaterFluxSum', 'timeMonthly_avg_sumGlobalStats_riverRunoffFluxSum', 'timeMonthly_avg_sumGlobalStats_iceRunoffFluxSum', 'timeMonthly_avg_sumGlobalStats_temperatureFluxSum', 'timeMonthly_avg_sumGlobalStats_salinityFluxSum', 'timeMonthly_avg_sumGlobalStats_salinityRestoringFluxSum', 'timeMonthly_avg_sumGlobalStats_landIceFreshwaterFluxSum', 'timeMonthly_avg_sumGlobalStats_accumulatedLandIceMassSum', 'timeMonthly_avg_sumGlobalStats_accumulatedLandIceHeatSum', 'timeMonthly_avg_sumGlobalStats_accumulatedLandIceFrazilMassSum', 'timeMonthly_avg_rmsGlobalStats_layerThicknessRms', 'timeMonthly_avg_rmsGlobalStats_normalVelocityRms', 'timeMonthly_avg_rmsGlobalStats_tangentialVelocityRms', 'timeMonthly_avg_rmsGlobalStats_layerThicknessEdgeRms', 'timeMonthly_avg_rmsGlobalStats_relativeVorticityRms', 'timeMonthly_avg_rmsGlobalStats_enstrophyRms', 'timeMonthly_avg_rmsGlobalStats_kineticEnergyCellRms', 'timeMonthly_avg_rmsGlobalStats_normalizedAbsoluteVorticityRms', 'timeMonthly_avg_rmsGlobalStats_pressureRms', 'timeMonthly_avg_rmsGlobalStats_montgomeryPotentialRms', 'timeMonthly_avg_rmsGlobalStats_vertVelocityTopRms', 'timeMonthly_avg_rmsGlobalStats_vertAleTransportTopRms', 'timeMonthly_avg_rmsGlobalStats_lowFreqDivergenceRms', 'timeMonthly_avg_rmsGlobalStats_highFreqThicknessRms', 'timeMonthly_avg_rmsGlobalStats_temperatureRms', 'timeMonthly_avg_rmsGlobalStats_salinityRms', 'timeMonthly_avg_rmsGlobalStats_layerThicknessPreviousTimestepRms', 'timeMonthly_avg_rmsGlobalStats_frazilLayerThicknessTendencyRms', 'timeMonthly_avg_rmsGlobalStats_evaporationFluxRms', 'timeMonthly_avg_rmsGlobalStats_rainFluxRms', 'timeMonthly_avg_rmsGlobalStats_snowFluxRms', 'timeMonthly_avg_rmsGlobalStats_seaIceFreshWaterFluxRms', 'timeMonthly_avg_rmsGlobalStats_riverRunoffFluxRms', 'timeMonthly_avg_rmsGlobalStats_iceRunoffFluxRms', 'timeMonthly_avg_rmsGlobalStats_temperatureFluxRms', 'timeMonthly_avg_rmsGlobalStats_salinityFluxRms', 'timeMonthly_avg_rmsGlobalStats_salinityRestoringFluxRms', 'timeMonthly_avg_rmsGlobalStats_landIceFreshwaterFluxRms', 'timeMonthly_avg_rmsGlobalStats_accumulatedLandIceMassRms', 'timeMonthly_avg_rmsGlobalStats_accumulatedLandIceHeatRms', 'timeMonthly_avg_rmsGlobalStats_accumulatedLandIceFrazilMassRms', 'timeMonthly_avg_avgGlobalStats_layerThicknessAvg', 'timeMonthly_avg_avgGlobalStats_normalVelocityAvg', 'timeMonthly_avg_avgGlobalStats_tangentialVelocityAvg', 'timeMonthly_avg_avgGlobalStats_layerThicknessEdgeAvg', 'timeMonthly_avg_avgGlobalStats_relativeVorticityAvg', 'timeMonthly_avg_avgGlobalStats_enstrophyAvg', 'timeMonthly_avg_avgGlobalStats_kineticEnergyCellAvg', 'timeMonthly_avg_avgGlobalStats_normalizedAbsoluteVorticityAvg', 'timeMonthly_avg_avgGlobalStats_pressureAvg', 'timeMonthly_avg_avgGlobalStats_montgomeryPotentialAvg', 'timeMonthly_avg_avgGlobalStats_vertVelocityTopAvg', 'timeMonthly_avg_avgGlobalStats_vertAleTransportTopAvg', 'timeMonthly_avg_avgGlobalStats_lowFreqDivergenceAvg', 'timeMonthly_avg_avgGlobalStats_highFreqThicknessAvg', 'timeMonthly_avg_avgGlobalStats_temperatureAvg', 'timeMonthly_avg_avgGlobalStats_salinityAvg', 'timeMonthly_avg_avgGlobalStats_layerThicknessPreviousTimestepAvg', 'timeMonthly_avg_avgGlobalStats_frazilLayerThicknessTendencyAvg', 'timeMonthly_avg_avgGlobalStats_evaporationFluxAvg', 'timeMonthly_avg_avgGlobalStats_rainFluxAvg', 'timeMonthly_avg_avgGlobalStats_snowFluxAvg', 'timeMonthly_avg_avgGlobalStats_seaIceFreshWaterFluxAvg', 'timeMonthly_avg_avgGlobalStats_riverRunoffFluxAvg', 'timeMonthly_avg_avgGlobalStats_iceRunoffFluxAvg', 'timeMonthly_avg_avgGlobalStats_temperatureFluxAvg', 'timeMonthly_avg_avgGlobalStats_salinityFluxAvg', 'timeMonthly_avg_avgGlobalStats_salinityRestoringFluxAvg', 'timeMonthly_avg_avgGlobalStats_landIceFreshwaterFluxAvg', 'timeMonthly_avg_avgGlobalStats_accumulatedLandIceMassAvg', 'timeMonthly_avg_avgGlobalStats_accumulatedLandIceHeatAvg', 'timeMonthly_avg_avgGlobalStats_accumulatedLandIceFrazilMassAvg', 'timeMonthly_avg_vertSumMinGlobalStats_layerThicknessMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_normalVelocityMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_tangentialVelocityMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_layerThicknessEdgeMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_relativeVorticityMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_enstrophyMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_kineticEnergyCellMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_normalizedAbsoluteVorticityMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_pressureMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_montgomeryPotentialMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_vertVelocityTopMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_vertAleTransportTopMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_lowFreqDivergenceMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_highFreqThicknessMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_temperatureMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_salinityMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_layerThicknessPreviousTimestepMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_frazilLayerThicknessTendencyMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_evaporationFluxMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_rainFluxMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_snowFluxMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_seaIceFreshWaterFluxMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_riverRunoffFluxMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_iceRunoffFluxMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_temperatureFluxMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_salinityFluxMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_salinityRestoringFluxMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_landIceFreshwaterFluxMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_accumulatedLandIceMassMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_accumulatedLandIceHeatMinVertSum', 'timeMonthly_avg_vertSumMinGlobalStats_accumulatedLandIceFrazilMassMinVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_layerThicknessMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_normalVelocityMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_tangentialVelocityMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_layerThicknessEdgeMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_relativeVorticityMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_enstrophyMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_kineticEnergyCellMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_normalizedAbsoluteVorticityMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_pressureMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_montgomeryPotentialMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_vertVelocityTopMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_vertAleTransportTopMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_lowFreqDivergenceMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_highFreqThicknessMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_temperatureMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_salinityMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_layerThicknessPreviousTimestepMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_frazilLayerThicknessTendencyMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_evaporationFluxMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_rainFluxMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_snowFluxMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_seaIceFreshWaterFluxMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_riverRunoffFluxMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_iceRunoffFluxMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_temperatureFluxMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_salinityFluxMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_salinityRestoringFluxMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_landIceFreshwaterFluxMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_accumulatedLandIceMassMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_accumulatedLandIceHeatMaxVertSum', 'timeMonthly_avg_vertSumMaxGlobalStats_accumulatedLandIceFrazilMassMaxVertSum', 'timeMonthly_avg_activeTracersSurfaceFlux_temperatureSurfaceFlux', 'timeMonthly_avg_activeTracersSurfaceFlux_salinitySurfaceFlux', 'timeMonthly_avg_activeTracersSurfaceFluxRunoff_temperatureSurfaceFluxRunoff', 'timeMonthly_avg_activeTracersSurfaceFluxRunoff_salinitySurfaceFluxRunoff', 'timeMonthly_avg_activeTracersSurfaceFluxRemoved_temperatureSurfaceFluxRemoved', 'timeMonthly_avg_activeTracersSurfaceFluxRemoved_salinitySurfaceFluxRemoved', 'timeMonthly_avg_nonLocalSurfaceTracerFlux_nonLocalTemperatureSurfaceFlux', 'timeMonthly_avg_nonLocalSurfaceTracerFlux_nonLocalSalinitySurfaceFlux']
ERROR: analysis task climatologyMapSSH: remapMpasClimatology failed during check and will not be run
ERROR: a subtask of analysis task climatologyMapSSH failed during check,
       so this task will not be run
```

**Comment by xylar** [comment]
@pwolfram, please test this branch with the anvil BGC run that caused this issue before.  I still think the preferred solution would be:
* disable MLD tasks in the generate option (as you have done)
* have the MLD tasks fail during ``setup_and_check`` because MLD was disabled in the run

I will add a commit to this PR to address the latter.

**Comment by xylar** [comment]
@pwolfram, this PR was at your request.  Please review when you have a chance.

**Comment by xylar** [comment]
@pwolfram, I tried calling but I'll respond on GitHub instead.  This PR *does* in fact solve the general issue (commit 5f07d4d) and not just the specific issue related to MLD (commit 86f1d0a).  I just wanted to clear that up since solving the general issue required a bit more planning and effort, and I initially thought it might not work.

**Comment by pwolfram** [comment]
@xylar, I see now-- sorry about the confusion.  Thanks, this is great!

**Pull request merged**
