### PR TITLE
Add a config file and job script for theta

### PR DESCRIPTION
**Pull request by xylar**
The theta job script needs an extra step of creating a bash wrapper around `run_mpas_analysis`.  This is because, without the wrapper, the job scheduler creates a symlink to `run_mpas_analysis`, meaning python no longer finds the `mpas_analysis` package.

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I have tested the config file both on the login node and via the batch script.  All analysis was successful on the login node. The analysis is still running in the batch script and I will update with the results in the morning.

**Comment by xylar** [comment]
@vanroekel and @stephenprice, could you please just copy over the job script and config file (as normal) and then set an output directory and make the job script point to the config file?  Could you let me know if you are able to run the analysis successfully in batch mode?  Any comments are most welcome.

**Comment by vanroekel** [comment]
@xylar it looks like theta is down for maintenance.  I will test as soon as it is back.

**Comment by xylar** [comment]
@vanroekel, great, thanks!  That's right, I read yesterday when I was learning how to do batch scripts on Theta that they do maintenance on Mondays.

**Comment by vanroekel** [comment]
@xylar I just tried this on theta and get an error I don't understand when using your job_script.theta.bash.  It is below
```
apsched: request exceeds max alloc
```
Any ideas on what I may have missed?  The bash script seems to only request one node so I'm confused.

**Comment by xylar** [comment]
@stephenprice, I'm going to go ahead and merge.  If you discover any issues, we can follow up with a future PR.

**Comment by xylar** [comment]
Thanks for testing and reviewing, @vanroekel

**Pull request merged**
