### PR TITLE
Add utility script for making ISMIP6 obs region masks

### PR DESCRIPTION
**Pull request by xylar**
This requires `geometric_features >= 0.2.0` and `mpas_tools >= 0.5.0`.

These regions were used in [Barthel et al. (2020)](https://doi.org/10.5194/tc-14-855-2020) and will be used in a paper we're working on, too.

### CODE REVIEW

**Comment by xylar** [comment]
Since `geometric_features >= 0.2.0` hasn't been released yet, CI will fail for now.

**Comment by xylar** [comment]
@alicebarthel, I'll ping you as soon as this is ready to review.  For now, I'm putting the PR ups so I can post test results before merging https://github.com/MPAS-Dev/geometric_features/pull/160 and making the release for that repo.

**Comment by xylar** [comment]
## Testing round 1

I built a test package of `geometric_features` 0.2.0 on Anvil, then ran the Anvil test suite:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/add_ismip6_features

The `timeSeriesOceanRegions` analysis ran successfully with the QU240wLI test data:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/add_ismip6_features/ismip6_regions/ocean/index.html

The region shapes look right, so I think this is good to go.  The config file for plotting just these regions is here:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/add_ismip6_features/ismip6_regions/ismip6_regions.cfg
(Part of the provenance of the web site, as usual.)

**Comment by xylar** [comment]
## Testing round 2

This time with the released `geometric_features` 0.2.0.

Here are the relevant config options I added to test ISMIP6 regions:
``` cfg
[timeSeriesOceanRegions]
## options related to plotting time series of groups of ocean regions

# the names of region groups to plot, each with its own section below
regionGroups = ['ISMIP6 Regions']


[timeSeriesISMIP6Regions]
## options related to plotting time series of Antarctic regions

# list of regions to plot or ['all'] for all regions in the masks file.
# See https://github.com/MPAS-Dev/geometric_features/blob/master/geometric_features/aggregation/ocean/ismip6_regions.py
# for the names of the regions.
regionNames = ['all']

# a list of variables to plot
variables = [{'name': 'temperature',
              'title': 'Temperature',
              'units': r'$^\circ$C',
              'mpas': 'timeMonthly_avg_activeTracers_temperature'},
             {'name': 'salinity',
              'title': 'Salinity',
              'units': 'PSU',
              'mpas': 'timeMonthly_avg_activeTracers_salinity'},
             {'name': 'potentialDensity',
              'title': 'Potential Density',
              'units': 'kg m$^{-3}$',
              'mpas': 'timeMonthly_avg_potentialDensity'},
             {'name': 'mixedLayerDepth',
              'title': 'Mixed Layer Depth',
              'units': 'm',
              'mpas': 'timeMonthly_avg_dThreshMLD'}]

# Observational data sets to compare against
obs = ['SOSE', 'WOA18']
```

**Comment by xylar** [comment]
@alicebarthel, could you try this out with one of the runs we want to analyze for our paper?

First, check out this branch.  If you have cloned the main repo (https://github.com/MPAS-Dev/MPAS-Analysis) into a directory `MPAS-Analysis`, then do the following from that directory:
```
git remote add xylar/MPAS-Analysis git@github.com:xylar/MPAS-Analysis.git
git fetch --all -p
git checkout -b add_ismip6_features xylar/MPAS-Analysis/add_ismip6_features
```
Then, set up your config file to point to the run you want, and run only the `timeSeriesOceanRegions` analysis.  Add config options for `timeSeriesOceanRegions` and `timeSeriesISMIP6Regions` as I have indicated above.

Make a conda environment that includes the latest `geometric_features`:
```
source ~/miniconda3/etc/profile.d/conda.sh
conda activate base
conda create -n mpas-analysis python=3.8 numpy scipy "matplotlib>=3.0.2" \
    netCDF4 "xarray>=0.14.1" dask bottleneck lxml "nco>=4.8.1" pyproj \
    pillow cmocean progressbar2 requests setuptools shapely "cartopy>=0.18.0" \
    cartopy_offlinedata "geometric_features>=0.2.0" gsw "pyremap<0.1.0" \
    "mpas_tools>=0.0.15" pandas python-dateutil six
```

Make sure your job script uses this environment, meaning it includes:
```
source ~/miniconda3/etc/profile.d/conda.sh
conda activate mpas-analysis
```

If you run into any trouble, let's chat here or on Slack.

**Comment by xylar** [comment]
@alicebarthel, I just updated this branch, just in case you were already using it.  Please
```
git fetch --all -p
git reset --hard xylar/MPAS-Model/add_ismip6_features
```
to pull in the latest changes.  They probably don't matter for what you're doing but it's a good idea.

**Comment by alicebarthel** [comment]
The analysis worked for B-ISMF at this stage. Could you correct the capitalization? under timeseries, the dir created is "iSMIP6Regions" and hte time series are all call iSMIP6Regions_<time period>.nc
Unless it is on purpose, I find the inconsistent capitalization confusing.

**Comment by alicebarthel** [comment]
Also, the analysis failed for B-noISMF. Investigating now.

**Comment by xylar** [comment]
@alicebarthel, thanks for the review!  I agree, `iSMIP6Regions` is a pretty ugly construction.  `antarcticRegions` and `southernOcean` aren't much better.  I'll see if I can fix that for all regions.  Probably tomorrow.

**Comment by xylar** [comment]
@alicebarthel, I've rerun the test analysis with the capitalization fix you requested.  See the image at the following link as an example of the renaming working as expected:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/add_ismip6_features/ismip6_regions/ocean/ISMIP6Regions_ISMIP6AmerySectorShelf_temperature.png

Could you update again (same instructions as before: https://github.com/MPAS-Dev/MPAS-Analysis/pull/777#issuecomment-772653773) and make sure you also see the expected capitalization?

**Comment by xylar** [comment]
@alicebarthel, I added a function and a utility script for creating the masks for the ISMIP6 regions on the ISMIP6 8 km grid.  The script runs quite quickly (compared to other sets of regions and meshes, at least).  The results are here:
https://drive.google.com/drive/folders/1JPXjtOuUWx0EncDzqNCv9yaIXsH6BKzX?usp=sharing

Hopefully, these will be easy for you to use.  Let me know how it goes, and include that in your review of this PR when you have the chance.

**Comment by xylar** [comment]
@alicebarthel, I have moved the mask creation code to MPAS-Tools: 
https://github.com/MPAS-Dev/MPAS-Tools/pull/406

The ISMIP6 regions will now come directly from geometric_features, so there is no extra work here to support them (unless we want to make MPAS-Analysis produce them by default, in which case some config options would need to change).

I have tested the utility script with a test build of https://github.com/MPAS-Dev/MPAS-Tools/pull/406 and it seems to work.  I'm going to go ahead and merge this once an appropriate MPAS-Tools release has happened since it now only creates a utility script that won't affect anyone else's work.

I don't think any more testing is needed from you for this particular PR, so I'm going to take you of as a reviewer.

**Pull request merged**
