### PR TITLE
Reorganize repo w/ scripts from on ACME analysis

### PR DESCRIPTION
**Pull request by xylar**
The repository has been reorganized using the five existing
analysis modules from the ACME PreAndPostProcessingScripts repo.
The mpas_analysis directory is set up to operate as a python
package.  To call the analysis driver, use:
python -m mpas_analysis.run_analysis <config_file>

A very messy example config file, config.analysis, is included
based on the combination of two config files (one automatically
generated and one edited by the user) from the ACME repo.

This reorganziation is seen only as a starting point for the
MPAs-Analysis repository.

### CODE REVIEW

**Comment by xylar** [comment]
@pwolfram or @toddringler , I don't seem to be a maintainer for this repo.  If one of you have the proper permissions, could you please add me and any of the rest of us that should be involved (e.g. Milena, Mark)

**Comment by xylar** [comment]
# Testing

I have made sure this repo can be used to exactly reproduce the existing ACME analysis for MPAS components.  This is the starting point for modifying the analysis to be more general.

**Comment by pwolfram** [comment]
@xylar, did that fix the permissions?  Also, assuming @milenaveneziani is ok with this it should be merged.

**Comment by xylar** [comment]
@pwolfram, yes, that fixed it.  Yes, I think @milenaveneziani should be the one to merge this, once the associate ACME PR has been merged.

@milenaveneziani, to the degree possible, I think we should try to follow a similar procedure for reviews to the one in MPAS-Dev/MPAS: https://github.com/MPAS-Dev/MPAS/wiki/Satisfying-Pull-Requests.  Let me know if that will work for you.

**Comment by xylar** [comment]
@milenaveneziani, you will need to checkout not only the main repo but also all the forks that exist so far. (You should probably create your own fork while you're at it.)  If you have any trouble, I think @pwolfram should be able to help but I can also try to help remotely.

**Comment by milenaveneziani** [comment]
@xylar, @pwolfram: yes, I know what to do (I am comfortable with the basic git stuff..). Thanks.
I have to leave earlier today, but I'll try to squeeze this in.

**Comment by xylar** [comment]
Okay, cool.  Sorry for assuming you didn't know your way around.  I wasn't sure because the other repo didn't seem to be using forks and such.  Also, I'm still kind of dumb with this stuff myself so I had to figure out how to add all the forks yesterday when I was checking out this repo for the first time.

**Comment by xylar** [comment]
@milenaveneziani, great, I see your fork and I just added it to my remotes.

**Comment by milenaveneziani** [comment]
@xylar: ok, I have a local branch tracking your fork. I have a few questions regarding the structure:
- since mpas_xarray.py is now down in share/mpas_xarray/, wouldn't it make more sense to put it in /share/io?
- in the structure we discussed through the google doc, we had two extra folders in share/: share/interp and share/temporal_stats. You don't want to add them at this point (empty, of course)?
- I guess the same question holds for the land_ice folder

One unrelated thing, about forks for the ACME PreAndPostprocessing repo: I will create a fork as soon as we start merging the coupled_diags stuff into master.

**Comment by xylar** [comment]
> since mpas_xarray.py is now down in share/mpas_xarray/, wouldn't it make more sense to put it in /share/io?

I guess I'm fine either way but I was concerned that a string like `mpas_analysis.shared.io.mpas_xarray.mpas_xarray` starts to get pretty long so I thought it might make sense to just make mpas_xarray part of shared directly.

> in the structure we discussed through the google doc, we had two extra folders in share/: share/interp and share/temporal_stats. You don't want to add them at this point (empty, of course)?

I guess I don't see any big advantage in putting in empty folders for now.  We can add the folders along with the appropriate scripts when we have them.

> I guess the same question holds for the land_ice folder

Again, I think we can add it when there are some land-ice diagnostics to populate it.

> One unrelated thing, about forks for the ACME PreAndPostprocessing repo: I will create a fork as soon as we start merging the coupled_diags stuff into master.

I think the way that repo works is that we aren't creating forks.  I think it's kind of a sloppy style so I'd prefer not to adopt it in MPAS repos, but it's best to stick with the conventions other users are adhering to in PreAndPostProcessingScripts itself and not to create your own fork.  You should just create your own branches within the existing repo as you have been, though there should be much less need to do so in the very near future.

**Comment by milenaveneziani** [comment]
sounds good, @xylar. I am going to merge it as is.

**Comment by xylar** [comment]
Thanks!

**Pull request merged**
