### PR TITLE
Split TimeSeriesAntarcticMelt into multiple subtasks

### PR DESCRIPTION
**Pull request by xylar**
One subtask computes time series data for all ice shelves, while the remaining subtasks each plot the time series for an individual ice shelf.

### CODE REVIEW

**Comment by xylar** [comment]
@stephenprice, this branch is based off of #482 so it's marked as "don't merge".  But you can take a look at these changes as well if you want to review both PRs at the same time.  I kept these changes separate just to make it clear which changes were related and which were mostly independent.  For this PR, you only need to review commit 2714505.

**Comment by stephenprice** [comment]
@xylar -- Thanks. I'll look this one over too.

**Comment by stephenprice** [comment]
@xylar -- I don't see anything that bothers me here. But I also have to admit that I'm probably not able to review this at a very critical level as my python skills are not up to par with the level of coding here. If you are happy with the additional input provided by Phillip then it's probably fine to merge these changes.

**Comment by xylar** [comment]
Thanks @stephenprice.  Again, mostly just checking to make sure you're okay with me messing with your code and the concepts behind my changes.  Happy to walk you through the python at some point if you like...

**Pull request merged**
