### PR TITLE
Rename the example meshes to new E3SMv2 names

### PR DESCRIPTION
**Pull request by xylar**
The renaming is in all example config files, `config.default` and the documentation.

### CODE REVIEW

**Comment by xylar** [comment]
@milenaveneziani, just pinging you for a thumbs up or thumbs down.

**Comment by xylar** [comment]
Actually, I think "names of ocean and sea ice meshes" should be "the name of the ocean and sea-ice mesh" (singular).  Yes?

**Comment by milenaveneziani** [comment]
good idea.

**Comment by xylar** [comment]
## Testing

This was tested as part of an analysis test-suite run on Chrysalis:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/chrysalis/add_new_transects_to_transport_time_series/

**Pull request merged**
