### PR TITLE
Enhance "error bars" for observations in Antarctic melt time series plots

### LINKED ISSUE #488: Improve visibility of observation error bars in time series plots
@stephenprice always has to add a box around the observations to make them more visible in talks.  We should just make this happen in the original python plots.

### PR DESCRIPTION
**Pull request by xylar**
Also, fix a bug from #483 that led to obs not being plotted.

closes #488

### CODE REVIEW

**Comment by xylar** [comment]
Example image before:
melt_rate_getz

and after:
melt_flux_getz

**Comment by xylar** [comment]
@stephenprice, if you could give the plots above a quick look and tell me if this looks okay to you, that would be great!  Suggestions are most welcome.  I just wanted to save you the trouble of having to put these kinds of boxes around the obs. manually in your talks going forward.

Also, feel free to have a look at the code if you have time.  There was a bug in #483 that led to obs not being plotted that I didn't notice until I was trying to make the obs more visible.

**Comment by stephenprice** [comment]
Thanks @xylar -- that looks perfect to me. Exactly what we've been doing in ppt to add a bit more visibility to them!

**Comment by xylar** [comment]
Thanks, @stephenprice.

**Pull request merged**
