### PR TITLE
Add starting point for documentation

### PR DESCRIPTION
**Pull request by xylar**
Add support for creating documentation using `sphinx`.

So far, only basic, autogenerated documentation of the API for all public module functions (except CI tests) is included.

Docstrings for `run_analysis.py`, `generalized_reader` and `mpas_xarray` have been updated to produce better formatting in autodocs.  In the future, all docstrings would need to be carefully checked and fixed as needed.

### CODE REVIEW

**Comment by xylar** [comment]
To try it out:
```
conda install sphinx
cd docs
make html
```
Then, open `_build/index.html` in your browser to see the results.

**Comment by xylar** [comment]
Eventually, we will want to use [Read the Docs](https://readthedocs.org/) to host our documentation and update it automatically from the repo.  This is what `xarray` does.  For now, we'll just work on making it useful.

**Comment by xylar** [comment]
Once we have this up and running, a requirement of each PR should be making sure the appropriate documentation is in place.  Hopefully, this is just a question of adding a very simple new test file like [here](https://github.com/MPAS-Dev/MPAS-Analysis/pull/158/files#diff-cff63bf3afecebfec56171b25afab23cR6) and makeing sure it's referenced somehwere like [here](https://github.com/MPAS-Dev/MPAS-Analysis/pull/158/files#diff-caf2a6b8f4947d018f68893c695b5202R23)

**Comment by xylar** [comment]
This is meant to address #3 (at least to the point where we can close the issue -- documenting the code will be an ongoing effort).

**Comment by xylar** [comment]
@pwolfram and @milenaveneziani, I'd like to push ahead with the documentation.  I just updated the work I had done back in March and a *lot* has changed since then so there was quite a bit of clean up to do just to get things back to how they were back then.  I think if we were making sure there was at least minimal documentation as we go, it would make things much easier.

@pwolfram, I know you haven't been very involved in MPAS-Analysis lately.  Let me know if you're interested in reviewing this PR.  I'd definitely appreciate your feedback.  Otherwise, feel free to take yourself off as a reviewer.

**Comment by xylar** [comment]
The current documentation as generated by sphinx can be found here:
http://portal.nersc.gov/project/m2833/xylar/mpas_analysis/docs/

Obviously, this is just a temporary location for convenience until we get things to a point that we're ready to put them up on some more permanent portal.

**Comment by xylar** [comment]
@vanroekel, your feedback would also be welcome.

**Comment by xylar** [comment]
@jhkennedy, I'd appreciate any suggestions you might have on our baby steps toward documentation here.

**Comment by milenaveneziani** [comment]
@xylar: I followed the link on the nersc portal and things look good to me, as they are supposed to, at least. A couple of clarification points for me following this statement:

> this may just be a question of adding any new classes and functions to api.rst so the documentation gets autogenerated from the docstring

So, with any new analysis task or any new function (even the internal ones, that start with `_`?), we need to add them to api.rst? And what does it need to happen for the documentation to be autogenerated? Do we hit the `make` command or is it done automatically? (sorry the simple questions..)

**Comment by xylar** [comment]
@milenaveneziani,
> So, with any new analysis task or any new function (even the internal ones, that start with _?), we need to add them to api.rst? 

No, I think you just should add the class name and any functions other than the obvious, required ones (`__init__`, `setup_and_check`, `run`) that other developers would need to know about.  Nothing with a `_` in front.  Similarly, with functions, you would only add them if you think another developer would want to know about them.

> And what does it need to happen for the documentation to be autogenerated? Do we hit the make command or is it done automatically? 

You go into the `docs` directory and do `make html`.  This doesn't happen automatically (though maybe we can make it automatic eventually).  It is "autogenerated" in the sense of you don't make the pages, they get generated from the docstrings automatically.

**Comment by xylar** [comment]
No, the more extensive documentation would need to be in the form of .rst files within the docs folder specific to different categories.  The docstrings would remain as they are, as would the autogenerated docs.  We would just also have better, more thorough documentation in addition.  Take a look at the xarray documentation as an example.
http://xarray.pydata.org/en/stable/

**Comment by milenaveneziani** [comment]
great. Thanks for the clarification.

**Comment by xylar** [comment]
@jhkennedy, I looked at your output and I don't understand the import errors you're getting.  It seems like almost nothing is importing properly for you, whereas I am not seeing those errors when I run `make html`.  I'll see if I can figure out how to reproduce the errors.  I was only seeing one import problem (for a function that was recently removed) and I have fixed it in my latest commit.

I'm aware of the syntax errors but don't plan on fixing them in this PR.  I will do a separate clean-up PR for that in the near future.  But I don't want cleaning up a bunch of docstrings to get in the way of having a basic structure for documentation.

Part of cleaning up docstrings will be making sure the "Authors" section is used consistently (rather than "Author".  Although this is a non-standard section, we agreed that we wanted to keep it for our own purposes.

**Comment by xylar** [comment]
I have moved `design_docs` to `docs/design_docs` as you suggest.  However, I don't think we want our design documents to become part of the documentation directly.  It could be helpful as a starting point for some of the documentation but these files are meant to document the process of designing new features, rather than providing documentation for developers.

**Comment by xylar** [comment]
@jhkennedy, I think I might know what went wrong with your test.
```bash
#!/usr/bin/env bash

conda create --name mpas -c conda-forge python=2 numpy scipy matplotlib netCDF4 xarray dask bottleneck basemap \
  lxml nco pyproj sphinx sphinx_rtd_theme numpydoc
# I think you may be missing the pillow library here.  The README.md needs to be fixed.

git clone git@github.com:xylar/MPAS-Analysis.git xylar-mpas-a
# I think you missed checking out the correct branch here, but I'm pretty sure you 
# did that step because nothing would have worked if you hadn't
cd xylar-mpas-a/docs

make html > >(tee make.out) 2> >(tee make.err >&2)
```

**Comment by xylar** [comment]
@jhkennedy, I can verify that I see the same errors you did when I am missing the pillow library.  Could you please add that library and try again?

**Comment by jhkennedy** [comment]
@xylar I did checkout sphinx_support -- I just forgot to pull that out of my history for the gist (updated). 

Adding `pillow` did fix all the import errors, I missed it because it's not listed in the `conda install...` command in `README.md`, so it might be good to add that to the install command (even though I now see it's listed on the line above). 

Looks like it's ready!

**Comment by xylar** [comment]
Thanks @jhkennedy.  I fixed the README.md here.  (I had actually fixed it in another PR, too, but that hasn't been merged yet.)

**Comment by xylar** [comment]
@pwolfram is quite busy.  @vanroekel and @milenaveneziani, anymore feedback before we merge this?

**Comment by xylar** [comment]
@milenaveneziani, there was a typo in the path command above.  Please try:
```
export PATH=/global/homes/z/zender/bin_${NERSC_HOST}:${PATH}
```

**Comment by xylar** [comment]
@milenaveneziani and @jhkennedy, I went ahead and fixed up a *bunch* of docstrings that weren't producing nice looking documentation.  Obviously, this shouldn't change the code itself in any way.  Just wanted to give you a heads up...

**Comment by xylar** [comment]
I just updated the example results at:
http://portal.nersc.gov/project/m2833/xylar/mpas_analysis/docs/

**Comment by xylar** [comment]
I will merge this tomorrow unless I get further feedback requesting changes.

**Comment by xylar** [comment]
At @jhkennedy's recommendation, I added our design documents at the end of the documentation.  This required some minor reformatting and also the use of the `recommonmark` package (which is only available through pip).  The README.md has been updated accordingly.

**Pull request merged**
