### PR TITLE
Fix path to ocean streams file in sea ice utility

### PR DESCRIPTION
**Pull request by xylar**
The path should be relative to base directory, not run directory.

### CODE REVIEW

**Comment by xylar** [comment]
@pwolfram, tests on Wolf exposed a bug in the fallback plan when there is not a sea ice restart file so we try to find an ocean streams file.  I will test this on Wolf right now to make sure it fixes the problem.  After that, I would appreciate if you woul have a look and merge ASAP.

**Comment by pwolfram** [comment]
@xylar, assuming tests pass on Wolf I'll merge once you get back to me.

**Comment by xylar** [comment]
Still debugging on wolf, I'm afraid.

**Comment by xylar** [comment]
Okay, got it.  Ready to merge.  I remove one more unneeded block in `sea_ice.modelvsobs`

**Comment by xylar** [comment]
Ready to merge...

**Comment by xylar** [comment]
Hmm, maybe I need to update the "last modified".  Just a sec.

**Comment by xylar** [comment]
Okay, ready to merge for reals this time.

**Pull request merged**
