### PR TITLE
Create MOC masks like other region masks

### PR DESCRIPTION
**Pull request by xylar**
Use the python mask functions and add date stamps to the files.

This requires newer versions of both `mpas_tools` and `geometric_features`.

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

This has been tested with the Anvil and Chrysalis test suites:
* [Anvil](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/anvil/update_moc_to_python_masks/)
* [Chrysalis](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/chrysalis/update_moc_to_python_masks/)

On Chrysalis, there was a strange file system issue with `climatologyMapArgoTemperature_plotJFM_latlon_depth_-25` related to copying a PNG file, but this appears to be unrelated to this PR.  Other than that, all tests ran successfully.  The expected mask-related files are being created, e.g.:
```
mocBasins20210331.geojson                
oQU480_mocBasins20210331.nc
oQU480_mocBasinsAndTransects20210331.nc
```

I also tested on a simulation with `WCAtl12to45E2r4` to make sure the MOC looks as expected:
* https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/chrysalis/update_moc_to_python_masks/20210326.v2beta3.piControl.ne30pg2_WCAtl12to45E2r4/

**Comment by xylar** [comment]
In the process of trying to debug #789, I realized that there are a number issues with this switch-over.
* The MOC analysis member may not work with the masks generated in this way because of the fields that are missing.  I need to check on this.
* The offline MOC definitely does rely on fields that aren't available this way, and I need to see why I'm not getting errors related to this during testing.

**Comment by milenaveneziani** [comment]
@xylar: to check things, I could create the MOC southern transect file for say, the EC30to60, using the new MPAS-Tool, and then compare it to the old file. How does that sound?

**Comment by xylar** [comment]
@milenaveneziani, that would be fine. The main thing to check is that the analysis runs without crashing on as many meshes as we can test.  I'll do some more checking myself.

**Comment by xylar** [comment]
I still need to address the issues related to the online AM, which will likely require an update to MPAS-Tools.  So no rush on testing this.

**Comment by xylar** [comment]
I will re-test this tomorrow with https://github.com/MPAS-Dev/MPAS-Tools/pull/407 and with more meshes.  Hopefully, Chrysalis will be behaving better.

**Comment by xylar** [comment]
@milenaveneziani, this is now fully ready to test and review.  Note that the latest `geometric_features` (0.4.0) and `mpas_tools` (0.5.0) are required.  If you want, you could test #794 instead (which also will include these changes as soon as I rebase in a moment).

**Comment by xylar** [comment]
@milenaveneziani, my testing isn't succeeding.  I think some of the changes from #794 are likely needed here.  I'm not sure if I'll figure it out tonight or tomorrow.

**Comment by milenaveneziani** [comment]
ok, I'll let you know how my testing of #794 goes.

**Comment by xylar** [comment]
@milenaveneziani, don't bother with testing.  I missed a critical commit in https://github.com/MPAS-Dev/MPAS-Tools/pull/407.  I can't believe how careless I'm being and how easily I'm getting confused!  I need to fix that and do yet another release of MPAS-Tools :-(

**Comment by milenaveneziani** [comment]
ok, no worries. Please don't beat yourself up, having many things on your plate is hard.

**Comment by xylar** [comment]
@milenaveneziani, I tested this again and updated the testing comment above.  This is finally ready for you to test and review when you're ready.

**Comment by milenaveneziani** [comment]
Thanks @xylar. Is it still OK/better to test this within #794?

**Comment by xylar** [comment]
@milenaveneziani, yes, let me rebase really quick...

**Comment by xylar** [comment]
Okay, #794 is rebased.  If you're testing on Chrysalis, you may notice the errors I fixed in #796 because I haven't rebased onto those changes yet.

**Comment by milenaveneziani** [comment]
I recreated all mask files in the process of testing #794 (all but the transportTransects masks), so I think we should be good with this one as well.

**Pull request merged**
