### PR TITLE
Adds travis continuous integration (CI) for pytest

### PR DESCRIPTION
**Pull request by pwolfram**
Continuous integration using pytest will help us avoid bugs and ensure that design objectives are being met via test.  

This merge adds the capability for Travis CI to run py.test to ensure that tests are passing.

### CODE REVIEW

**Comment by pwolfram** [comment]
@xylar, I'll let you know when this is setup right

**Comment by pwolfram** [comment]
@xylar and @mark-petersen, this is ready to review.  We pass on python 2.7 but not on python 3.5.  This begs the question of which version of python we should support for the long term.  See issue #43

**Comment by pwolfram** [comment]
Note, I could remove 3.5 for now so that the CI for our current repo passes.  This may be the way to go and I'll do this unless there are objections.

**Comment by pwolfram** [comment]
Note, if this passed pytest we would have a green check mark.

**Comment by xylar** [comment]
@pwolfram, I think you should take out the python 3.5 checks for now.  We can add it back after we have altered the repo to support python 3.5 (or as part of that transition, since it would be a helpful way of checking if we've done things right).

**Comment by xylar** [comment]
@pwolfram, can you either explain here a bit more about how this works or point me to some simple documentation (if such a thing exists) that you used to know how to set this up?  I'd like to understand what happens in the GitHub repo vs. what happens on the travis-ci.org.  How is the script `py.test` assembled or where does it reside?  What does that script look like?

**Comment by pwolfram** [comment]
@xylar, `py.test` is equivalent to `py.test` and is just how the testing suite is being ran.  I just followed xarray's approach and the travis-ci.org quick-start documentation.  I'm not doing anything fancy from here otherwise.

**Comment by pwolfram** [comment]
@xylar, I've removed the 3.5 test as requested for now.  It isn't too hard to add it back.

**Comment by pwolfram** [comment]
@xylar, as far as I'm concerned this can be merged now.  @mark-petersen, here is both an implementation an example of how this works.  The only thing that needed to be done beside this code was turning on the travis-ci switch for this repo at https://travis-ci.org/profile/MPAS-Dev

**Comment by xylar** [comment]
>  `py.test` is equivalent to `pytest` and is just how the testing suite is being ran. I just followed xarray's approach and the travis-ci.org quick-start documentation. I'm not doing anything fancy from here otherwise.

Ah, I see.  That makes sense. then.

**Comment by xylar** [comment]
Nice!  @pwolfram, don't forget to delete your remote branch since I can't.

**Comment by xylar** [comment]
Oops, sorry!  I missed that the `don't merge` flag was still on.  Let me know if you wanted to make more changes.

**Comment by pwolfram** [comment]
No problem @xylar, I did realized I forgot the CI badge for the readme, however.  So we need to add that in, but that isn't a big deal.

**Comment by pwolfram** [comment]
See #44

**Pull request merged**
