### PR TITLE
Add North Atlantic and North Pacific comparison grids

### LINKED ISSUE #859: Contour plots on projection grids
The code for plotting contours on projection grids is not handling the fact that we are supplying the corners, rather than the centers, of grid cells.  This needs to be fixed to allow for plots on projection grids that include contours (currently `climatologyMapSSH`).

```
Plotting 2-d maps of Zero-mean SSH climatologies for JFM on the north_atlantic grid...
analysis task climatologyMapSSH_plotJFM_north_atlantic failed during run
Traceback (most recent call last):
  File "/gpfs/fs1/home/ac.xylar/mpas-work/analysis/add_north_atlantic_pacific_comparison_grids/mpas_analysis/shared/analysis_task.py", line 330, in run
    self.run_task()
  File "/gpfs/fs1/home/ac.xylar/mpas-work/analysis/add_north_atlantic_pacific_comparison_grids/mpas_analysis/ocean/plot_climatology_map_subtask.py", line 446, in run_task
    self._plot_projection(remappedModelClimatology,
  File "/gpfs/fs1/home/ac.xylar/mpas-work/analysis/add_north_atlantic_pacific_comparison_grids/mpas_analysis/ocean/plot_climatology_map_subtask.py", line 583, in _plot_projection
    plot_projection_comparison(
  File "/gpfs/fs1/home/ac.xylar/mpas-work/analysis/add_north_atlantic_pacific_comparison_grids/mpas_analysis/shared/plot/climatology_map.py", line 652, in plot_projection_comparison
    plot_panel(ax, modelTitle, modelArray, **dictModelRef)
  File "/gpfs/fs1/home/ac.xylar/mpas-work/analysis/add_north_atlantic_pacific_comparison_grids/mpas_analysis/shared/plot/climatology_map.py", line 578, in plot_panel
    ax.contour(x, y, array, levels=contours, colors=lineColor,
  File "/home/ac.xylar/anvil/miniconda3/envs/mpas_dev/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 318, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ac.xylar/anvil/miniconda3/envs/mpas_dev/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 362, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ac.xylar/anvil/miniconda3/envs/mpas_dev/lib/python3.10/site-packages/cartopy/mpl/geoaxes.py", line 1666, in contour
    result = matplotlib.axes.Axes.contour(self, *args, **kwargs)
  File "/home/ac.xylar/anvil/miniconda3/envs/mpas_dev/lib/python3.10/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/ac.xylar/anvil/miniconda3/envs/mpas_dev/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 6301, in contour
    contours = mcontour.QuadContourSet(self, *args, **kwargs)
  File "/home/ac.xylar/anvil/miniconda3/envs/mpas_dev/lib/python3.10/site-packages/matplotlib/contour.py", line 812, in __init__
    kwargs = self._process_args(*args, **kwargs)
  File "/home/ac.xylar/anvil/miniconda3/envs/mpas_dev/lib/python3.10/site-packages/matplotlib/contour.py", line 1441, in _process_args
    x, y, z = self._contour_args(args, kwargs)
  File "/home/ac.xylar/anvil/miniconda3/envs/mpas_dev/lib/python3.10/site-packages/matplotlib/contour.py", line 1480, in _contour_args
    x, y, z = self._check_xyz(args[:3], kwargs)
  File "/home/ac.xylar/anvil/miniconda3/envs/mpas_dev/lib/python3.10/site-packages/matplotlib/contour.py", line 1521, in _check_xyz
    raise TypeError(f"Length of x ({nx}) must match number of "
TypeError: Length of x (427) must match number of columns in z (426)
```

### PR DESCRIPTION
**Pull request by xylar**
This merge makes a number of changes needed to support projection grids other than the Arctic and Antarctic that were previously provided.

Projection information is moved to the `mpas_analysis.shared.projection` module.  Both `pyproj.Proj` and `cartopy.crs.Projection` projections are provided for each supported grid.  (This is because there is currently no way to convert directly from one to the other.)

Grid descriptors for the supported projections are updated to handle the new organization structure.  Comparison grids may provide a height as well as a width in the config options (since these are typically not the same for general projections).

Plotting on polar projection grids is generalized to plot on any projection grid.  Several hard-coded parameters (figure sizes, latitude/longitude line spacing and whether the coastline is plotted) are now config options for each projection grid.

Some poorly formatted docstrings have been fixed, and most docstrings that explicitly listed the available comparison grids have been changed to `str` instead to make it easier to add new comparison grids without onerous changes to these docstring.

Ocean tasks and subtasks have been updated to be consistent with these changes.  In particular, the subtask for plotting climatology maps has been updated fairly extensively.

Note: currently, no analysis uses the new comparison grids by default.  We may wish to change this.  I plan to at least add these projection grids to testing.

closes #859

### CODE REVIEW

**Comment by xylar** [comment]
Here is some example analysis (at very coarse resolution):
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/anvil/add_north_atlantic_pacific_comparison_grids/test_proj/ocean/index.html

image
image

**Comment by xylar** [comment]
## Testing

I ran the full test suite on Anvil:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/anvil/add_north_atlantic_pacific_comparison_grids/
All analysis was generated successfully and the North Atlantic and North Pacific plots are there in all the tests I looked at.

**Comment by xylar** [comment]
Note that `climatologyMapSSH` can't currently be plotted on the new projection grids because of #859.

**Comment by xylar** [comment]
It turned out to be a 3-line fix to get contours working so I'm including that here as well:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis_testing/anvil/add_north_atlantic_pacific_comparison_grids/test_ssh_proj/ocean/index.html#north_atlantic_ssh

image

**Comment by milenaveneziani** [comment]
Looks great, @xylar.

**Review by milenaveneziani — APPROVED** [review]

**Comment by xylar** [comment]
@milenaveneziani, thanks for having a look!

**Comment by ytakano3** [comment]
@xylar Thank you for the updates, I tested with the simulation from Kuroshio RRM, so far the plot looks great (huge anomaly appears because of initial adjustment this is just after the spin-up started).

I will also try plotting SSH (with contours) and bgc variables.

sstHADOI_north_atlantic_GMPAS-JRA-RYF8485_Kuroshio12to60E2r1_chrysalis-bgc1-test3-10yrs-co2_1958_ANN_years0008-0010
sstHADOI_north_pacific_GMPAS-JRA-RYF8485_Kuroshio12to60E2r1_chrysalis-bgc1-test3-10yrs-co2_1958_ANN_years0008-0010

**Comment by xylar** [comment]
@ytakano3, do you have permission to review?   Go to the "Files changed" tab and see if you see the green "Review changes" button in the upper right.
image
If not, no worries.  I'd just like to have an "official" review if possible.

**Review by ytakano3 — APPROVED** [review]
I looked through the changes in codes, more focus on plotting and settings for North Atlantic and North Pacific part, the default settings look good (and I checked the results testing my self). Please go ahead and proceed.

**Comment by ytakano3** [comment]
@xylar I agree with you, discussion will be in another place on physics but certainly needs more spin-up. From the Paraview animation, the changes SST shows eddy in the North Pacific, which is what we expected.

**Comment by xylar** [comment]
Thank you very much @ytakano3 and @milenaveneziani.  @ytakano3, these new projection grids and the capability to add new ones as we like is a really nice feature to have.  Thank you for pushing for it.

**Pull request merged**
