### PR TITLE
Removed necessity of having ocean streams file for seaice analysis

### PR DESCRIPTION
**Pull request by akturner**
Several of the sea ice scripts require ocean streams file to be present that will not be for sea ice stand alone simulations. Altered code so that they are not opened unless necessary.

### CODE REVIEW

**Comment by xylar** [comment]
Oops, nice fix, @akturner .  I'm surprised by tests worked.

**Comment by akturner** [comment]
@xylar: Thanks! Pretty simple fix.

**Comment by milenaveneziani** [comment]
Thanks for checking and fixing this @akturner. I am guessing our tests worked because we tested on ACME runs, so great that Adrian could test on sea-ice standalone. Adrian: did everything else work?

**Comment by milenaveneziani** [comment]
ah, just saw you opened an issue.

**Comment by akturner** [comment]
@milenaveneziani: Thanks Milena, yes the second metric didn't work. Not sure it should have done since I havent made mapping files yet, but dont think that was the problem.

**Comment by xylar** [comment]
So I tried by test (using the file in `configs/lanl/config.20170207.MPAS-SeaIce.QU60km_polar.wolf`) and it fails just as @akturner found.  With this fix I can confirm that the time-series tests work.  Until I get the general horizontal interpolation code working (soon hopefully) we won't have a mapping file to test the climatology metrics.

**Comment by xylar** [comment]
Thanks @akturner.  I'll go ahead and merge this fix.

**Comment by xylar** [comment]
@akturner, I'm not able to delete your remote branch because this is a public repository.  If you'd like to delete it yourself, you can do so here on GitHub.

**Comment by akturner** [comment]
@xylar: Thanks for adding this!

**Pull request merged**
