### PR TITLE
Re-introduced the option to turn off comparison with ACMEv0 pre-processed data

### PR DESCRIPTION
**Pull request by milenaveneziani**
- Changed scripts (including the run script and the config file) to optionally skip the visualization of pre-processed ACME-v0 data.
- Added config.analysis_* and config.analysis.* to .gitignore.

### CODE REVIEW

**Comment by milenaveneziani** [comment]
I tested this on edison, using the usual ACME v1 run results, by first setting ref_case_v0 equal to the ACME-v0 case for which I have data available. The results were bfb with respect to the previous run made with the old code. I then set ref_case_v0=None, and the script ran smoothly again, producing the plots without the ACME-v0 results, as expected.

**Comment by milenaveneziani** [comment]
I also tested this successfully on wolf, using a QU_480km test case that @mark-petersen ran in standalone MPAS-O. This is also relevant in the sense that the framework works for single MPAS components (turning off the bits of the code that are not relevant to the particular standalone run, of course).
If someone is willing to take a look at the python changes introduced here, I think this PR could be ready to merge. Unless we want to test the git submodule thing with the ACME PreAndPostProcessing repo first. What do you think @mark-petersen?

**Comment by xylar** [comment]
@mark-petersen, I've assigned you to review this PR.  Let me know if you're too busy and maybe @pwolfram or I can do it instead.  But I'm assuming you can coordinate best with @milenaveneziani how these changes get pulled into the ACME PreAndPostProcessingScripts repo.

**Comment by mark-petersen** [comment]
Great.  I was able to modify a few lines in the configure script to point to my directories.  It ran and made the SST plot above the first time I tried it.  Beautiful!  Thanks everyone for your work on this.

**Comment by mark-petersen** [comment]
@milenaveneziani I usually delete the branch of the person who made the pull request.  It looks like I don't have permission to do that for you:
```
wf-fe2.lanl.gov> git push milena :milena/fix_compare_ocnice_tov0
To git@github.com:milenaveneziani/MPAS-Analysis.git
 ! [remote rejected] milena/fix_compare_ocnice_tov0 (permission denied)
error: failed to push some refs to 'git@github.com:milenaveneziani/MPAS-Analysis.git'
```

**Comment by milenaveneziani** [comment]
Thanks @mark-petersen! I don't know how to change the permissions, but I deleted the branch.
Glad it worked out fine.

**Comment by xylar** [comment]
@mark-petersen and @milenaveneziani, I think the permissions of the repo are such that we're not allowed to delete (or otherwise modify) each other's forks.  Perhaps that's because this is a public repo?  Doug would know... ;-p

**Comment by douglasjacobsen** [comment]
@xylar Yup, you're definitely correct. Public fork repos are owned by the person who forked, rather than the organziation (like private fork repos).

You can add collaborators (and maybe teams?) to the fork, but typically you would just ask the owner to delete them.

**Pull request merged**
