### PR TITLE
Fix climatology computations with single months

### PR DESCRIPTION
**Pull request by xylar**
With this merge, climatologies are successfully for individual months (Jan, Jul, etc.)

### CODE REVIEW

**Comment by xylar** [comment]
This should fix #425.

**Comment by xylar** [comment]
@bradyrx, could you rebase onto this branch (or cherry-pick the commit) and check that it fixes the issue you saw in #425?

**Comment by xylar** [comment]
## Testing

I ran the analysis on the `climatologyMapSST` task with `seasons =  ['Jan', 'Jul', 'JFM', 'ANN']`.  Before this merge, I saw the same issues as in #425, but the climatologies were produced as expected with the merge.

I plan to do some more thorough testing to make sure I didn't break anything later today.

**Comment by xylar** [comment]
@milenaveneziani, since this is a bug fix, I'd like to get it merged before v1.0 if possible.  Let me know if you'll have some time for testing in the next few days.

**Comment by milenaveneziani** [comment]
sure, I'll run a test by tomorrow, after edison comes back.

**Comment by bradyrx** [comment]
@xylar, I rebased onto this branch and ran a test case with BGC for individual months (as well as some seasons) and all worked just fine.

**Comment by milenaveneziani** [comment]
Just did a test on edison, using the E3SM piControl and computing climos for Jan and May over year 450-455. All worked well for me too. Thanks @xylar for fixing this quickly.

**Comment by xylar** [comment]
Thanks @milenaveneziani and @bradyrx for testing.

**Pull request merged**
