### PR TITLE
Use chunking to reduce memory for Antarctic Melt time series

### PR DESCRIPTION
**Pull request by xylar**
Analysis is performed in chunks of 1 year and 10 regions.

### CODE REVIEW

**Comment by xylar** [comment]
@matthewhoffman, could you see if this branch allows you to compute melt rates with the full 156 year (or whatever) duration of the B case?  If you wait a couple of hours, I'll install E3SM-Unified 1.2.5 on Edison and Cori and you can try using that so you don't run into NCO version issues.  If you want to test sooner, you'll need to set up your own conda environment or use @czender's version of NCO.

**Comment by matthewhoffman** [comment]
@xylar , I just cherry-picked your commit to try this out.  I still get an error, but it's different.  This is what it is:
```
Error 11: Resource temporarily unavailable
analysis task timeSeriesAntarcticMelt_computeMeltRates failed during run
Traceback (most recent call last):
  File "mpas_analysis/shared/analysis_task.py", line 320, in run
    self.run_task()
  File "mpas_analysis/ocean/time_series_antarctic_melt.py", line 295, in run_task
    totalMeltFlux.compute()
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/p
ython2.7/site-packages/xarray/core/dataarray.py", line 659, in compute
    return new.load(**kwargs)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/p
ython2.7/site-packages/xarray/core/dataarray.py", line 633, in load
    ds = self._to_temp_dataset().load(**kwargs)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/p
ython2.7/site-packages/xarray/core/dataset.py", line 491, in load
    evaluated_data = da.compute(*lazy_data.values(), **kwargs)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/p
ython2.7/site-packages/dask/base.py", line 402, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/p
ython2.7/site-packages/dask/threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/p
ython2.7/site-packages/dask/local.py", line 505, in get_async
    raise_exception(exc, tb)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/p
ython2.7/site-packages/dask/local.py", line 274, in execute_task
    result = _execute_task(task, data)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/p
ython2.7/site-packages/dask/local.py", line 255, in _execute_task
    return func(*args2)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/p
ython2.7/site-packages/dask/array/core.py", line 89, in getter
    c = np.asarray(c)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/p
ython2.7/site-packages/numpy/core/numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/python2.7/site-packages/xarray/core/indexing.py", line 624, in __array__
    self._ensure_cached()
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/python2.7/site-packages/xarray/core/indexing.py", line 621, in _ensure_cached
    self.array = NumpyIndexingAdapter(np.asarray(self.array))
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/python2.7/site-packages/numpy/core/numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/python2.7/site-packages/xarray/core/indexing.py", line 602, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/python2.7/site-packages/numpy/core/numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/python2.7/site-packages/xarray/core/indexing.py", line 508, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/python2.7/site-packages/xarray/backends/netCDF4_.py", line 66, in __getitem__
    array = getitem(self.get_array(), key.tuple)
  File "netCDF4/_netCDF4.pyx", line 4119, in netCDF4._netCDF4.Variable.__getitem__
  File "netCDF4/_netCDF4.pyx", line 5036, in netCDF4._netCDF4.Variable._get
  File "netCDF4/_netCDF4.pyx", line 1754, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: Resource temporarily unavailable
```

It seems kind of suspicious if it's a real error or not.  But the rest of the analysis ran successfully, so I'm guessing it is.

**Comment by xylar** [comment]
Thanks, @matthewhoffman. That looks like a real error.  I'll see what I can figure out.

**Comment by xylar** [comment]
@matthewhoffman, I'm trying to debug this but don't have permission to read this file:
```
/global/cscratch1/sd/hoffman2/acme_scratch/edison/20190306.A_WCYCL1850-DIB-ISMF_CMIP6.ne30_oECv3wLI.edison/run/mpaso.rst.0157-01-01_00000.nc
```
Could you fix that?  (I really wish we could find a way to just set permissions and have them stick!)

**Comment by matthewhoffman** [comment]
@xylar , ok permission should be fixed now.  Sorry about that.

**Comment by xylar** [comment]
Thanks, @matthewhoffman

**Comment by xylar** [comment]
@matthewhoffman, the online searches I've done suggest that this might be an issue in an older version of xarray that should be fixed now.  I'm not exactly sure if the version of xarray in e3sm-unified 1.2.4 (which you are using) is old enough to have this issue.  But I ran the full analysis on your branch using e3sm-unified 1.2.5, which I just installed, and it got to 99% done before my job timed out (bad luck!).  I'm rerunning again without a purge to finish the last bit, at which point I'll post the results here.

If you are willing, would you also test with e3sm-unified 1.2.5?  I know it's a pain but I'm afraid that we won't know if the issue is fixed unless you also test it.  You should be able to just run with this branch because the latest e3sm-unified has all the required packages for the latest mpas-analysis.

**Comment by matthewhoffman** [comment]
@xylar , no problem, I'll try this again with 1.2.5 - that's easy now that you've created the package.

**Comment by xylar** [comment]
Here was my successful run of the analysis:
https://portal.nersc.gov/project/m2833/xylar/20190306.A_WCYCL1850-DIB-ISMF_CMIP6.ne30_oECv3wLI.edison/130-156/

**Comment by matthewhoffman** [comment]
@xylar , my analysis finally finished successfully!  The full analysis took 4:45 on Cori-Haswell using one task.  Previously, it had been a little under 2 hrs, but that was for a shorter time-series, with 6 tasks, and on Edison.  If that duration does not seem a concern to you, I will approve this PR.  I did check in the log for the execution time for all the melt rate tasks, and each one appeared to just take a few seconds.  The exception is this one, which I believe is the one you modified:
```
\Computing Antarctic melt rate time series...
  Load melt rate data...
Execution time: 0:03:09.35
```
3 minutes certainly sounds reasonable for that task.

I tested #560 , #566 , and #569  together and all worked.

**Comment by xylar** [comment]
@matthewhoffman, I've been having *terrible* problems with i/o lag on Edison and Cori.  I suspect that contributed to your long execution time.

There's definitely no need to run on 1 task.  I ran with 12 (I think) and it went just fine.

Thanks for the review!

**Pull request merged**
