### PR TITLE
Check for enough data in anomaly and Nino34 tasks; fix MOC time series with 1 year of data

### LINKED ISSUE #543: Add the badges from conda-forge
Current build status
====================

All platforms:
[noarch](https://circleci.com/gh/conda-forge/mpas-analysis-feedstock)

Current release info
====================

| Name | Downloads | Version | Platforms |
| --- | --- | --- | --- |
| [Conda Recipe](https://anaconda.org/conda-forge/mpas-analysis) | [Conda Downloads](https://anaconda.org/conda-forge/mpas-analysis) | [Conda Version](https://anaconda.org/conda-forge/mpas-analysis) | [Conda Platforms](https://anaconda.org/conda-forge/mpas-analysis) |

### LINKED ISSUE #545: Various issues are showing up with analysis of 1 year of simulation data
There is an issue with `timeSeriesMOC` reading from and writing to the same file.

Various tasks (`indexNino34` and `timeSeries*Anomaly`) that do a running mean fail during the run phase whereas they should fail during setup_and_check()

### PR DESCRIPTION
**Pull request by xylar**
The anomaly tasks cannot meaningfully run on a year or less of data.  They now all check during setup to see if there is sufficient data an fail with a warning if not.  (The reason for the failure is not given unless the --verbose tag is used.)

Add text telling users to get more info with the `--verbose` tag

Don't overwrite MOC time series if the yearly and total data are the same

Add conda-forge badges (unrelated but a convenient place to do this).

closes #545 
closes #543

### CODE REVIEW

**Comment by xylar** [comment]
I will probably do a v1.2.2 release after this fix, since it affects a lot of users who are testing on small data sets.

**Comment by xylar** [comment]
@darincomeau and @stephenprice, I'm still seeing errors so this is not ready to test yet.  I'll keep you posted.

**Comment by xylar** [comment]
Okay, @darincomeau and @stephenprice, this is ready to test on 1 year of data (and more if you like).  I rebased off of the commit just before v1.2 so you can run with this using E3SM-Unified.

**Comment by stephenprice** [comment]
Ok thanks. I will give it a try and get back to you.

**Comment by xylar** [comment]
@stephenprice, could you approve this based on your tests you showed me earlier today?

**Pull request merged**
