### PR TITLE
Plot production, melt iceberg concentration on projection grids

### PR DESCRIPTION
**Pull request by xylar**
This merge switches the remaining sea-ice climatology maps to be plotted on projection grids rather than lat-lon grids.  There are significant artifacts from the lat-lon grid when fields are plotted in polar stereographic projections as was done previously.  Since these have nothing to do with the model itself, they are just a distraction.  Resolution of the comparison grid is also unnecessarily low.  These issues are mitigated by comparing on the projection grid instead.

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

My run of the test suite is here:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xasay-davis/analysis_testing/chrysalis/plot_prodcution_melt_on_projection/

@darincomeau, it did, indeed, work on the first try.  Suspicious....

**Comment by xylar** [comment]
@darincomeau, could you have a look at this as soon as you have time?

**Comment by darincomeau** [comment]
@xylar I tested this here - looks good to me: https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.dcomeau/20221104.CRYO1950.ne30pg2_ECwISC30to60E2r1.N2Dependent.submeso.chrysalis/yrs1-5/sea_ice/index.html#arctic_extended_nh_production

For reference, here's the same run with the old projection:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.dcomeau/20221104.CRYO1950.ne30pg2_ECwISC30to60E2r1.N2Dependent.submeso.chrysalis/yrs1-10/sea_ice/index.html#nh_production

The projection plots look the same to me, but I'm not sure I know what to look for.

**Review by darincomeau — APPROVED** [review]
Approved based on above testing.

**Comment by xylar** [comment]
@darincomeau, thanks!

The difference is pretty obvious to me.  If I look at:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.dcomeau/20221104.CRYO1950.ne30pg2_ECwISC30to60E2r1.N2Dependent.submeso.chrysalis/yrs1-10/sea_ice/seaice_meltingNH_CRYO1950.ne30pg2_ECwISC30to60E2r1.N2Dependent.smep_ANN_years0001-0010.png
I see pixellated rings.

If I look at:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.dcomeau/20221104.CRYO1950.ne30pg2_ECwISC30to60E2r1.N2Dependent.submeso.chrysalis/yrs1-5/sea_ice/seaice_meltingNH_arctic_extended_CRYO1950.ne30pg2_ECwISC30to60E2r1.N2Dependent.smep_ANN_years0001-0005.png
they're gone.

**Pull request merged**
