### PR TITLE
Add README.md to the documentation as a quick start guide

### PR DESCRIPTION
**Pull request by xylar**
This merge also makes some updates to the README:
* ACME --> E3SM
* Improved instructions for installing
* Moved developer-related details to the developer section

### CODE REVIEW

**Comment by xylar** [comment]
This was surprisingly easy and I think the results look pretty good.

**Comment by xylar** [comment]
Addressed #370

**Comment by milenaveneziani** [comment]
Is that OK if I approve this visually, or would you prefer me to generate a new documentation page?

**Comment by milenaveneziani** [comment]
I ran `make html` using my own conda environment: I got a whole bunch of warning messages, but the result seems fine to me. You can take a look here:
http://portal.nersc.gov/project/acme/milena/mpas-analysis_documentation/

**Comment by xylar** [comment]
@milenaveneziani, yep, there are a number of warnings that we decided we can live with.  The ones I see are related to the tables extracted from the obs. database and @pwolfram said there's little we can do about them since they relate to an external package (tabulate) that we're calling.

Thanks for testing!

**Pull request merged**
