### PR TITLE
Reformatted OHC and other time series plots

### PR DESCRIPTION
**Pull request by milenaveneziani**
Reformatted OHC time series plot as well as other time series plots (SST, MOC and sea-ice).
Added a legendText to `timeseries_analysis_plot` and `timeseries_analysis_plot_polar`.

This is to address #229.

### CODE REVIEW

**Comment by milenaveneziani** [comment]
New plots can be seen here:
http://portal.nersc.gov/project/acme/milena/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edisonTest/

**Comment by milenaveneziani** [comment]
@xylar, @vanroekel: I have decided to leave the other time series (SST, MOC and sea-ice) without legends for now, but I changed their title and line colors to make things more consistent with the changes in the OHC plot.
I think the OHC plot should look very similar to Luke's version now.
Let me know what you think.

**Comment by xylar** [comment]
I tested this on my laptop and the plots come out just like in the example @milenaveneziani posted.

**Comment by milenaveneziani** [comment]
Thanks @xylar for reviewing this on your day off.
What do you think of these new version:
http://portal.nersc.gov/project/acme/milena/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edisonTest/

I have set the color for the main run to black and that for the reference run to blue (red seems to draw too much attention to me).

**Comment by milenaveneziani** [comment]
ok, I changed the blue to red. I also played a bit more with a the '+' linestyle, but ended up not changing it.
I will assume @vanroekel is OK with these changes (since they mimic his script) and merge shortly.

**Pull request merged**
