### PR TITLE
Plot no more than 300 pluses in OHC plot

### PR DESCRIPTION
**Pull request by xylar**
Otherwise the plot with pluses can become indistinguishable from a thick line.

### CODE REVIEW

**Comment by xylar** [comment]
See #286, which this PR is intended to address.

**Comment by xylar** [comment]
Before:
image
After:
image

**Comment by milenaveneziani** [comment]
Tested with this and the previous merge to develop and all looks nice:
http://portal.nersc.gov/project/acme/milena/B_low_res_ice_shelves_1696_JWolfe_layout_Edison/

glad we were able to get a few of these in in the last couple of days! Thanks @xylar.

**Comment by xylar** [comment]
@milenaveneziani, thanks for the review!  Yes, I agree that it's been nice to make some progress and get a number of things off the issues list this week.

**Pull request merged**
