### PR TITLE
Remove variable, namelist and stream maps

### PR DESCRIPTION
**Pull request by xylar**
These were intended to handle different MPAS/ACME versions but
the names of variables, namelist options and streams seem to have
settled down.  For any future changes, we plan to have specific
MPAS-Analysis tags that are compatible with specific ACME and MPAS
versions without any guarantee of backward compatibility.

### CODE REVIEW

**Comment by xylar** [comment]
Developers trying to set up new analysis tasks are likely to find the namelist, stream and variable maps confusing to follow.  It is hard to tell sometimes which MPAS variable corresponds with which MPAS-Analysis variable.  Since we have an alternative plan for handling changes in variable names going forward, @milenaveneziani and I agreed that it would be reasonable to remove the maps.

**Comment by xylar** [comment]
## Testing

The analysis for an ACME beta1 G-QU240 test case ran as normal with no errors.

**Comment by xylar** [comment]
Addresses #223

**Comment by milenaveneziani** [comment]
@xylar: I would like to test this on previous MPAS versions to see where things break (I know they do brake for alpha runs, but I don't remember if beta0 is OK). The reason I want to test beta0 is that we have a beta0 run that we use for testing a-prime on some machines (like OLCF and aims4/acme1). If things break on beta0, it just means that we need to transfer a newer case for testing on those machines. Also, the longest ACME run we have so far is a beta0 run, although I don't think that run will ever be used for publications.

**Comment by milenaveneziani** [comment]
So, I remembered correctly: this code without the variable maps fails on beta0 mpas-cice diagnostics, because we didn't have xtime_start and xtime_end in mpas-cice in beta0.

**Comment by xylar** [comment]
@milenaveneziani, yes, that's correct.  It would be beneficial to have a few different beta1 test data sets on AIMS4/ACME1 (and OLCF, too, but I can't help there).  I'm happy to move some over.  I'll include one with ice-shelf cavities, since analysis that only works in those runs is coming down the pipe.

**Comment by milenaveneziani** [comment]
And we could just use the v0.4 tag for analyzing the beta0 run, right?

I am pretty sure we already have a beta1 dataset on aims4/acme1, but we need to transfer it over to OLCF. Will do.

**Comment by xylar** [comment]
Your v0.43 tag should still work for beta0, so that's the one I would use.

**Comment by milenaveneziani** [comment]
I have tested this on beta1 and things work as expected.

**Pull request merged**
