### PR TITLE
Switch from WOA18 to WOA23

### PR DESCRIPTION
**Pull request by xylar**
This PR adds a preprocessing script for WOA23 and updates 3 analysis tasks, `climatologyMapWoa`, `timeSeriesOceanRegions` and `regionalTSDiagrams`, to use WOA23 instead of WOA18.

The observational database and documentation have also been updated.

Checklist
* [x] User's Guide has been updated
* [x] Documentation has been [built locally](https://mpas-dev.github.io/MPAS-Analysis/latest/users_guide/quick_start.html#generating-documentation) and changes look as expected
* [x] `Testing` comment in the PR documents testing used to verify the changes

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I ran the test suite on this branch.  Results are here:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xasay-davis/analysis_testing/chrysalis/switch-to-woa23/

While the simulations used in the test suite are coarse, it is clear to me that the observations look as expected for plots from all 3 tasks.

However, we will want to run analysis on some higher resolution simulations to be sure.

**Comment by xylar** [comment]
I expect WOA23 to be an especially big improvement on the Antarctic continental shelf because there's a bunch more seal data and such.

A next step (in a follow-up PR) would be to add transect plots at the same locations as our SOSE transects.  At the same time, we may wish to modify those transects.

**Comment by xylar** [comment]
@milenaveneziani, I want to make sure you're okay with this change.  I'm having trouble deciding who else might want to take the time to review.

**Comment by xylar** [comment]
## Higher res testing

I ran this analysis (and #1033) on 2 higher res simulations.

Here are results from a 2-year Icos30 simulation:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis/woa23/20241029.GMPAS-JRA1p5-DIB-DISMF.TL319_IcoswISC30E3r5.fix_total_ismf.chrysalis/

And here are results from years 31-39 of a SORRM simulation:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis/woa23/20241018.v3.SORRME3r3.piControl.scaledDISMF.chrysalis/yrs31-39/

I think all the analysis (climatology maps and different depths, constant lines on regional time series plots, T-S diagrams and transects) look as I expected.  If one wants to compare with WOA18, this set of analysis uses it instead of WOA23:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.dcomeau/E3SMv3_dev/20241018.v3.SORRME3r3.piControl.scaledDISMF.chrysalis/mpas_analysis/develop/yrs31-39/

The differences are subtle and mostly near the surface from what I'm seeing in the climatology maps.  Here's an example.
WOA18:
image

WOA23:
image

**Comment by milenaveneziani** [comment]
To be honest, I don't really see the differences.. Looks good to me.

**Review by milenaveneziani — APPROVED** [review]

**Comment by cbegeman** [comment]
@xylar I took a look. The biggest differences I see are here:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.dcomeau/E3SMv3_dev/20241018.v3.SORRME3r3.piControl.scaledDISMF.chrysalis/mpas_analysis/develop/yrs31-39/ocean/temperatureWOA18_antarctic_v3.SORRM.piControl-DISMF_depth_-50_JAS_years0031-0039.png vs https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis/woa23/20241018.v3.SORRME3r3.piControl.scaledDISMF.chrysalis/yrs31-39/ocean/temperatureWOA23_antarctic_v3.SORRM.piControl-DISMF_depth_-50_JAS_years0031-0039.png

But I agree that it all looks very similar so little harm in switching

**Comment by cbegeman** [comment]
And diffs here:
https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.dcomeau/E3SMv3_dev/20241018.v3.SORRME3r3.piControl.scaledDISMF.chrysalis/mpas_analysis/develop/yrs31-39/ocean/salinityWOA18_arctic_v3.SORRM.piControl-DISMF_depth_-50_JFM_years0031-0039.png vs. https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis/woa23/20241018.v3.SORRME3r3.piControl.scaledDISMF.chrysalis/yrs31-39/ocean/salinityWOA23_arctic_v3.SORRM.piControl-DISMF_depth_-50_JFM_years0031-0039.png

**Comment by xylar** [comment]
@milenaveneziani and @cbegeman, thank you both for having a look.  I have to say that I agree, I don't see as much difference as I was expecting to.  I had the impression that more seal data was being used but then I see that the bathymetry dataset is complete nonsense in the Amundsen Sea (likely elsewhere) and this significantly negates the usefulness of these updates for us.  For example:
image

**Comment by xylar** [comment]
I'm going to chat with @irenavankova about this and #1033 tomorrow and presumably merge after we discuss.

**Comment by milenaveneziani** [comment]
oh, that's a problem! I wonder if it's a woa23 issue that woa18 didn't have? I'm glad you looked at the sections.

**Comment by milenaveneziani** [comment]
I am looking at these two plots:
WOA18: https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.dcomeau/E3SMv3_dev/20241018.v3.SORRME3r3.piControl.scaledDISMF.chrysalis/mpas_analysis/develop/yrs31-39/ocean/index.html#antarctic_temperatureSose&gid=53&pid=16
WOA23: https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.xylar/analysis/woa23/20241018.v3.SORRME3r3.piControl.scaledDISMF.chrysalis/yrs31-39/ocean/temperatureWOA23_antarctic_v3.SORRM.piControl-DISMF_depth_-800_ANN_years0031-0039.png
I think I see the same issue, where the ice cavities are not entirely represented, especially in EA, Amery, and Fris.

**Comment by xylar** [comment]
@milenaveneziani, that was my conclusion as well.  I don't have a quick way to plot transects for WOA18 but I think the problem was inherited from earlier WOA versions.  It leaves me with a lot less confidence in the WOA climatologies broadly that this has gone unnoticed and/or uncorrected for so long.

**Comment by xylar** [comment]
Looking into EN4, it seems tricky, too.  It's pretty low res (maybe that's the best the data justifies) and it's either a collection of vertical profiles or a linear combination of the observations over a given month and a climatology covering 1970-2000.  So that's messy.

**Comment by alicebarthel** [comment]
Thanks for pointing out the bathymetry issue @xylar, I did not realize it was so bad. I know that WOD ends up with data that gets cut out of WOA due to the bathymetry choice. Given that the issues are already present for WOA18, updating to WOA23 sounds fine by me.

**Comment by xylar** [comment]
For the Southern Ocean, I know that folks at BAS are working on a better climatology from the mid 2000s on. (They are involved in ISMIP7.)  But there's no intention of making that a global climatology as far as I'm aware so it would need to be stitched together with something global.  Even though that sounds messy, that's the direction I would be tempted to go once that product is available.  We already do something like this for topography because GEBCO isn't up-to-date enough for Antarctica.

For MPAS-Analysis, the BAS product could be like SOSE where it's just used in the Southern Ocean.

**Comment by xylar** [comment]
@alicebarthel, thanks for taking a look and for your thoughts.  It's annoying to learn that this bathymetry problem is a known issue (at least from the WOD perspective) that has persisted.

**Comment by xylar** [comment]
@irenavankova also thinks this is useful despite the weird bathymetry.  So I'm merging this and #1033

**Pull request merged**
