### PR TITLE
Fix lat/lon axis limits for WOCE with bounds

### LINKED ISSUE #546: Degree bounds not being adjusted in WOCE transects
I just realized that the degree bounds that we print on the top axis of the transects, are not being adjusted when a subset of the transect is plotted (WOCE transects; see #539).
See this for example:
image

### PR DESCRIPTION
**Pull request by xylar**
If the x axis gets bounds, the lat/lon at the top now reflect this.

closes #546

### CODE REVIEW

**Comment by xylar** [comment]
@milenaveneziani, this seems to work for me.  Could you see if you have any luck?

temperaturetransect_woce_a12_prime_meridian_20180514 g oqu240wli edison_ann_years0001-0001

**Comment by milenaveneziani** [comment]
great, thanks @xylar, I'll try this asap.

**Comment by milenaveneziani** [comment]
@xylar: I reran the analysis that I have done recently (without purging, so that it would go fast), and I am seeing two problems:
1) the latitude axis should be inverted (should go from south to north when going from left to right). See my result here (but it is visible in your plots above as well):
temperaturetransect_woce_a21_drake_passage_theta 20180906 branch_nocnt a_wcycl1950s_cmip6_hr ne120_orrs18v3_icg_ann_years0016-0055

2) the SOSE transects give me an error:
```
Plotting Velocity Magnitude at 318.0$\degree$ Longitude over season JAS...
analysis task soseTransects_plotJAS_lon_318.0_velocityMagnitude failed during run
Traceback (most recent call last):
  File "mpas_analysis/shared/analysis_task.py", line 320, in run
    self.run_task()
  File "mpas_analysis/ocean/plot_transect_subtask.py", line 359, in run_task
    self._plot_transect(remappedModelClimatology, remappedRefClimatology)
  File "mpas_analysis/ocean/plot_transect_subtask.py", line 531, in _plot_transect
    contourLabelPrecision=contourLabelPrecision)
  File "mpas_analysis/shared/plot/plotting.py", line 1235, in plot_vertical_section_comparison
    contourLabelPrecision=contourLabelPrecision)
  File "mpas_analysis/shared/plot/plotting.py", line 1907, in plot_vertical_section
    linewidths=lineWidth)
  File "/lus/theta-fs0/projects/ccsm/acme/tools/e3sm-unified/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2918, in contour
    ret = ax.contour(*args, **kwargs)
  File "/lus/theta-fs0/projects/ccsm/acme/tools/e3sm-unified/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/python2.7/site-packages/matplotlib/__init__.py", line 1867, in inner
    return func(ax, *args, **kwargs)
  File "/lus/theta-fs0/projects/ccsm/acme/tools/e3sm-unified/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 6280, in contour
    contours = mcontour.QuadContourSet(self, *args, **kwargs)
  File "/lus/theta-fs0/projects/ccsm/acme/tools/e3sm-unified/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/python2.7/site-packages/matplotlib/contour.py", line 890, in __init__
    kwargs = self._process_args(*args, **kwargs)
  File "/lus/theta-fs0/projects/ccsm/acme/tools/e3sm-unified/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/python2.7/site-packages/matplotlib/contour.py", line 1476, in _process_args
    x, y, z = self._contour_args(args, kwargs)
  File "/lus/theta-fs0/projects/ccsm/acme/tools/e3sm-unified/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/python2.7/site-packages/matplotlib/contour.py", line 1546, in _contour_args
    self._contour_level_args(z, args)
  File "/lus/theta-fs0/projects/ccsm/acme/tools/e3sm-unified/base/envs/e3sm_unified_1.2.4_py2.7_nox/lib/python2.7/site-packages/matplotlib/contour.py", line 1223, in _contour_level_args
    self.levels = np.asarray(self.levels).astype(np.float64)
ValueError: could not convert string to float: none
```
Error is similar for all the SOSE transects, not just for the velocity magnitude one.

**Comment by xylar** [comment]
Thanks, @milenaveneziani.  I didn't have time to do more thorough testing and that was clearly needed.  I'll try to fix both of these right away.

**Comment by milenaveneziani** [comment]
no problem @xylar. This test took me less than half an hour to complete, just because I already had all set up to go.

**Comment by xylar** [comment]
@milenaveneziani, I looked at things carefully and I think the latitude/longitude are right.  The Drake Passage transect goes from north to south and we plot transects in the order they are presented (i.e. the direction the ship actually went).  This is one reason I was hoping we would have an inset map with a label of the start and finish of the transect, but Greg didn't get that work done (and didn't push anything to the branch on his fork).

**Comment by xylar** [comment]
If you want the option to reverse the WOCE transects, that could be another config option.

**Comment by xylar** [comment]
Maybe the way to do that would be to put the higher x value first and the lower value second.  I'll see if that already works.

**Comment by xylar** [comment]
Yep, it does:
temperaturetransect_woce_a12_prime_meridian_20180514 g oqu240wli edison_ann_years0001-0001

Does that work for you, @milenaveneziani?

**Comment by milenaveneziani** [comment]
I see now, I didn't realize the drake passage went from north to south (because I was focusing on A23 before, which does go from south to north). So, the trick is just to choose a different range in the config file (instead of going from 0 to 200 km, we would have to go from max-200 to max, whatever that max is).

**Comment by milenaveneziani** [comment]
are you saying that I could choose 800 to 600 and things just work? nice.
I will test a case with max=big number (say 6000km) and see if things work (because I really want to see the Antarctic coast, not the Patagonian one :)

**Comment by xylar** [comment]
> are you saying that I could choose 800 to 600 and things just work?

Yep!

> I will test a case with max=big number (say 6000km) and see if things work (because I really want to see the Antarctic coast, not the Patagonian one :)

That transect is actually only 830.8 km long.

**Comment by xylar** [comment]
I think I've fixed the SOSE transect issue (I was just trying to do some clean up).  I'll do some more testing.

**Comment by xylar** [comment]
## Testing

The usual 3 QU240wLI tests passed (py2.7, py3.7, ctrl v ref).

**Pull request merged**
