### PR TITLE
Switch example config files to use mapping directory

### PR DESCRIPTION
**Pull request by xylar**
This should have been part of #224, which switched the code to using a single mapping file directory rather than requiring that all mapping files be specified individually.

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

I ran the EC60to30 test on Edison and found that a mapping subdirectory was not created in the output directory, as expected, and the analysis proceeded as expected.

Calls to ncremap are using the pre-computed mapping files as expected:
```
...
Input #00: /scratch1/scratchdirs/xylar/analysis/EC60to30.beta1/fix_mapping/clim/mpas/mld_masked_oEC60to30v3/mpaso_JFM_001101_002003_climo.nc
Map/Wgt  : /scratch1/scratchdirs/xylar/analysis/EC60to30.beta1/fix_mapping/mapping/map_oEC60to30v3_to_0.5x0.5degree_bilinear.nc
Regridded: /scratch1/scratchdirs/xylar/analysis/EC60to30.beta1/fix_mapping/clim/mpas/remapped/mld_masked_oEC60to30v3_to_0.5x0.5degree/mpaso_JFM_001101_002003_climo.nc
...
```

**Comment by xylar** [comment]
This PR is intended to address #265.

**Comment by xylar** [comment]
@milenaveneziani, if you have time in the next day or 2, could you run a quick test (maybe at LANL IC) to make sure mapping files that have been cached aren't being recreated?  Thanks!

If things work as expected and you're happy with my fixes here, feel free to just approve the PR and I'll merge it myself.

**Comment by xylar** [comment]
@milenaveneziani, this would be the easier review and the higher priority over #258, in case you only have time for one or the other in the next couple of days.

**Comment by milenaveneziani** [comment]
@xylar: is that OK if I add the config file that I have been using on titan? It's nice to have it as an example because it refers to a short-term archived run.
I will test with that now.

**Comment by milenaveneziani** [comment]
The test passed with the config file I mentioned above on titan. I will push that now, and then I think this can be merged.

**Comment by xylar** [comment]
Thanks @milenaveneziani.  And, yes, feel free to add new config files like you did if they aren't redundant with existing ones.  We don't want to have an overwhelming number but for different resolutions or simulation length or that kind of thing, it's useful to have several config files on each machine.

**Pull request merged**
