### PR TITLE
Add NCO_PATH_OVERRIDE='No' before NCO calls

### PR DESCRIPTION
**Pull request by xylar**
This prevents NCO from using @czender's local version of NCO instead of our own NCO version on DOE LCF machines.

### CODE REVIEW

**Comment by xylar** [comment]
This is intended to address #245

**Comment by xylar** [comment]
## Testing

I have verified that an ACME G-QU240 case runs as excepted on my laptop and on edison.  I have verified from the `ncclimo` output that it is using `ncclimo` and `ncks` from the expected directory (acme-unified) rather than `~zender`.

**Comment by xylar** [comment]
Note: I had the following in my `.bashrc.ext` on edison, which caused problems when running `ncclimo`:
```
module unload python
```
@milenaveneziani, if you happen to have the same thing in your .`bashrc.ext` (most likely because you copied it from me), please remove it or comment it out.  It will mess up the path within `ncclimo`.

**Comment by milenaveneziani** [comment]
@xylar, to clarify: do I need anything in my bashrc at all, 'module load a certain python' or point to a certain path, as far as python and nco are concerned?

**Comment by milenaveneziani** [comment]
@xylar: FYI, I have the following in my .bashrc.ext on edison and they don't seem to cause any problem with ncclimo:
```
module unload python
module unload python_base
module use /global/project/projectdirs/acme/software/modulefiles/all
module load python/anaconda-2.7-acme
```

my test for this PR passed.

**Comment by xylar** [comment]
@milenaveneziani, what you have is fine.  What it wouldn't allow you to do is change to a different python than `python/anaconda-2.7-acme` because as soon as you call `ncclimo` (which is a bash script) it would load `python/anaconda-2.7-acme` and it would then use other NCO stuff from that python.  For me, this has been a problem because I use different python environments for different tasks (e.g. POPSICLES) so I now don't load any python at all in my `.bashrc.ext` and I now see that I also need to not *unload* any python there either.  Sounds like it's nothing you need to worry about.

**Comment by xylar** [comment]
Thanks for merging!

**Comment by milenaveneziani** [comment]
@xylar: this is good to know.

**Pull request merged**
